'use client';
import { useCallback, useEffect, useState } from 'react';
import SkillEditor from './SkillEditor';
import TaskBoard from './TaskBoard';
import { Overview, download, request, when } from './data';
import s from './AgentCenter.module.css';

export default function AgentCenter(){
 const [tab,setTab]=useState('connections'),[data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[client,setClient]=useState('codex'),[copied,setCopied]=useState(false),[tool,setTool]=useState('macro_calendar'),[args,setArgs]=useState('{}'),[result,setResult]=useState(''),[running,setRunning]=useState(false);
 const refresh=useCallback(async()=>{try{setData(await request<Overview>('overview'));setError('');}catch(e){setError(String(e));}finally{setLoading(false);}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),15000);return()=>clearInterval(timer);},[refresh]);
 const profile=data?.profiles.find(p=>p.id===client),selectedTool=data?.tools.find(t=>t.name===tool);
 async function copy(){try{await navigator.clipboard.writeText(profile?.content||'');setCopied(true);}catch{setError('Clipboard tidak tersedia. Pilih teks konfigurasi atau gunakan Download config.');}}
 async function run(){setRunning(true);setResult('');try{setResult(JSON.stringify(await request('tools/call',{name:tool,arguments:JSON.parse(args)}),null,2));void refresh();}catch(e){setResult(String(e));}finally{setRunning(false);}}
 return <section className={s.root} aria-label="Agent Center"><header className={s.hero}><div><span className={s.eyebrow}>AGT / AGENT INTEGRATION</span><h1>Satu workspace.<br/><em>Banyak agent.</em></h1><p>Hubungkan MCP, bagikan skills, dan bawa hasil riset kembali ke dashboard.</p></div><div className={s.heroAside}><strong>{data?`${data.tools.length} data tools · ${data.skills.length} skills`:'Memuat integrasi…'}</strong><span>Codex · Claude · Antigravity · stdio MCP</span><small>Client menjalankan agent; dashboard menyediakan data dan task inbox.</small></div></header>
 <nav className={s.tabs} aria-label="Agent Center sections">{[{id:'connections',label:'Connections'},{id:'tools',label:'Tool explorer'},{id:'skills',label:'Skills'},{id:'tasks',label:'Tasks & results'},{id:'activity',label:'Activity'}].map(t=><button key={t.id} aria-current={tab===t.id?'page':undefined} onClick={()=>setTab(t.id)}>{t.label}</button>)}<button onClick={()=>void refresh()} aria-label="Refresh Agent Center">↻</button></nav>
 <div className={s.body}>{error&&<p role="alert" className={s.error}>{error}<button onClick={()=>void refresh()}>Coba koneksi lagi</button></p>}{loading&&<div role="status" className={s.empty}>Memeriksa gateway dan layanan dashboard…</div>}
 {data&&<>
 {tab==='connections'&&<><div className={s.heading}><div><span className={s.eyebrow}>CONNECT YOUR CLIENT</span><h2>Konfigurasi yang siap dipakai</h2><p>Pilih client, gabungkan konfigurasi MCP, lalu reload koneksinya.</p></div><a className={s.linkButton} href="/?view=agent&ticker=SPY">Buka Quant Agent chat ↗</a></div><div className={s.clientChoices}>{data.profiles.map(p=><button key={p.id} aria-pressed={client===p.id} onClick={()=>{setClient(p.id);setCopied(false);}}>{p.id}</button>)}</div>
 {profile&&<div className={s.split}><section className={s.panel}><span className={s.eyebrow}>{profile.transport.toUpperCase()} / LOCAL CONNECTION</span><h3>{client}</h3><ol><li>Jalankan <code>start_dashboard.cmd</code>.</li><li>Gabungkan entry <code>vrp-dashboard</code> ke <strong>{profile.location}</strong>.</li><li>Reload MCP di client, lalu minta agent memanggil <code>dashboard_overview</code>.</li></ol><p>Bundle berisi konfigurasi, SKILL.md dan referensi. Tidak mengubah setting client secara otomatis. Path konfigurasi berlaku untuk komputer ini.</p><div className={s.actions}><a className={s.linkButton} href={`/api/agent-center/bundle/${client}`} download>Download bundle ZIP</a><button onClick={()=>download(profile.filename,profile.content)}>Download config</button></div></section><section className={s.panel}><div className={s.heading}><h3>Preview konfigurasi</h3><button onClick={copy}>{copied?'Tersalin':'Copy config'}</button></div><textarea aria-label="Konfigurasi MCP" readOnly className={s.config} value={profile.content} spellCheck={false}/><p>Credential lokal dibaca oleh bridge. Konfigurasi ini tidak berisi API key model.</p></section></div>}
 <div className={s.heading}><div><h2>Layanan data</h2><p>Status backend terukur. Client sightings ada di Activity setelah agent membuat permintaan MCP.</p></div></div><div className={s.services}>{data.services.map(service=><div key={service.name}><span className={s.dot} data-ready={service.ready}/><strong>{service.name}</strong><span>:{service.port}</span><small>{service.ready?'Responding':'Unavailable'}</small></div>)}</div><p className={s.notice}>MCP standar stdio cocok untuk client lokal. ChatGPT/cloud agent yang tidak bisa mengakses komputer ini memerlukan deployment terautentikasi tersendiri.</p></>}
 {tab==='tools'&&<><div className={s.heading}><div><span className={s.eyebrow}>ONE REGISTRY / UI + MCP</span><h2>Tool explorer</h2><p>Uji query data lewat jalur yang sama dengan agent eksternal.</p></div></div><div className={s.split}><aside className={s.list}>{data.tools.map(t=><button disabled={running} key={t.name} aria-pressed={tool===t.name} onClick={()=>{setTool(t.name);setArgs(JSON.stringify(t.example,null,2));setResult('');}}><strong>{t.name}</strong><small>{t.description}</small></button>)}</aside><section className={s.panel}><h3>{tool}</h3><p>{selectedTool?.description}</p><label>Arguments JSON<textarea value={args} onChange={e=>setArgs(e.target.value)} className={s.config} spellCheck={false}/></label><button disabled={running} onClick={run}>{running?'Mengambil data…':'Jalankan query'}</button><details><summary>Input schema</summary><pre className={s.output}>{JSON.stringify(selectedTool?.inputSchema,null,2)}</pre></details><div className={s.heading}><h3>Output</h3><button disabled={!result} onClick={()=>download(`${tool}.json`,result,'application/json')}>Download output</button></div><pre role="status" className={s.output}>{result.slice(0,24000)||'Hasil query muncul di sini.'}</pre>{result.length>24000&&<p>Preview dibatasi 24.000 karakter. Download untuk output lengkap.</p>}</section></div></>}
 {tab==='skills'&&<SkillEditor skills={data.skills} refresh={()=>void refresh()}/>}
 {tab==='tasks'&&<TaskBoard jobs={data.jobs} skills={data.skills} refresh={()=>void refresh()}/>}
 {tab==='activity'&&<><div className={s.heading}><div><h2>Client sightings & query log</h2><p>Nama client berasal dari profil lokal; waktu terakhir terlihat bukan bukti proses masih berjalan.</p></div></div><div className={s.services}>{data.clients.map(c=><div key={c.id}><strong>{c.name}</strong><small>{when(c.last_seen)}</small><code>{c.id.slice(0,8)}</code></div>)}</div>{!data.clients.length&&<p className={s.empty}>Belum ada permintaan dari client MCP. Pasang profil, lalu panggil dashboard_overview.</p>}<div className={s.tableWrap}><table><thead><tr><th>Waktu</th><th>Client</th><th>Query</th><th>Status</th><th>Durasi</th></tr></thead><tbody>{data.audit.map(a=><tr key={a.id}><td>{when(a.at)}</td><td>{a.client}</td><td>{a.tool}</td><td>{a.ok?'Success':'Failed'}</td><td>{a.duration.toFixed(2)}s</td></tr>)}</tbody></table>{!data.audit.length&&<p className={s.empty}>Belum ada query data yang dicatat.</p>}</div></>}
 </>}
 </div><footer className={s.footer}>VRP Agent Center · MCP tools / resources / prompts · tasks and skill revisions persist locally</footer></section>;
}
