'use client';
import { useState } from 'react';
import { Skill, download, request } from './data';
import s from './AgentCenter.module.css';
export default function SkillEditor({skills,refresh}:{skills:Skill[];refresh:()=>void}) {
 const [id,setId]=useState(skills[0]?.id||'my-research-skill'),[content,setContent]=useState(skills[0]?.content||''),[revision,setRevision]=useState(skills[0]?.revision||0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [fresh,setFresh]=useState(false);
 async function save(){setBusy(true);setMessage('');try{const r=await request<{revision:number}>(`skills/${encodeURIComponent(id)}`,{content,revision});setRevision(r.revision);setFresh(false);setMessage('Skill tersimpan. Download ulang bundle untuk memperbarui salinan di client.');refresh();}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 return <div className={s.split}><aside className={s.list}><h2>Skill library</h2><p>Instruksi portable untuk workflow agent.</p>{skills.map(skill=><button key={skill.id} disabled={busy} aria-pressed={id===skill.id} onClick={()=>{setId(skill.id);setContent(skill.content);setRevision(skill.revision);setFresh(false);setMessage('');}}><strong>{skill.id}</strong><small>{skill.description}</small></button>)}<button disabled={busy} onClick={()=>{setId('my-research-skill');setContent('---\nname: my-research-skill\ndescription: Describe when this research workflow should be used.\n---\nRead vrp://guide. Use dashboard_catalog before querying data.\n');setRevision(0);setFresh(true);setMessage('');}}>+ Skill baru</button></aside>
 <section className={s.panel}><div className={s.heading}><div><span className={s.eyebrow}>SKILL.MD / REVISION {revision}</span><h2>Editor workflow</h2></div><button onClick={()=>download('SKILL.md',content)}>Download .md</button></div><label>Nama skill<input value={id} disabled={!fresh||busy} onChange={e=>setId(e.target.value)} maxLength={60}/></label><label>Instruksi SKILL.md<textarea className={s.editor} value={content} onChange={e=>setContent(e.target.value)} maxLength={30000} spellCheck={false}/></label><p>Frontmatter harus berisi name yang sama dan description. Skill adalah instruksi; menyimpan tidak menjalankan kode.</p><button disabled={busy} onClick={save}>{busy?'Menyimpan…':'Simpan skill'}</button>{message&&<p role="status" className={s.notice}>{message}</p>}</section></div>;
}
