'use client';
import { useEffect, useState } from 'react';
import { Job, Skill, download, request, when } from './data';
import s from './AgentCenter.module.css';
export default function TaskBoard({jobs,skills,refresh}:{jobs:Job[];skills:Skill[];refresh:()=>void}){
 const [title,setTitle]=useState(''),[prompt,setPrompt]=useState(''),[target,setTarget]=useState('any'),[skill,setSkill]=useState('vrp-job-worker'),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Job|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const updated=jobs.find(j=>j.id===selected)?.updated;
 useEffect(()=>{let active=true;if(!selected){setDetail(null);return;}request<Job>(`jobs/${selected}`).then(d=>{if(active)setDetail(d);}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[selected,updated]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const j=await request<Job>('jobs',{title,prompt,target,skill});setSelected(j.id);setDetail(j);setTitle('');setPrompt('');refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function cancel(){if(!detail)return;setBusy(true);try{setDetail(await request<Job>(`jobs/${detail.id}/cancel`,{}));refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <><div className={s.heading}><div><span className={s.eyebrow}>DASHBOARD → AGENT → RESULT</span><h2>Research task inbox</h2><p>Buat tugas, lalu minta agent pilihan lu mengambilnya lewat MCP. Halaman memperbarui status tiap 15 detik.</p></div></div>
 <div className={s.split}><form className={s.panel} onSubmit={create}><h3>Tugas baru</h3><label>Judul tugas<input required minLength={3} maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Analisis reaksi BTC setelah CPI"/></label><label>Target agent<select value={target} onChange={e=>setTarget(e.target.value)}>{['any','codex','claude','antigravity','generic'].map(v=><option key={v}>{v}</option>)}</select></label><label>Skill tugas<select value={skill} onChange={e=>setSkill(e.target.value)}><option value="">Tanpa skill</option>{skills.map(v=><option key={v.id} value={v.id}>{v.id}</option>)}</select></label><label>Instruksi tugas<textarea required minLength={10} maxLength={16000} rows={7} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Tujuan, aset, periode, data yang harus dibaca, dan bentuk hasil…"/></label><button disabled={busy}>{busy?'Menyimpan…':'Buat tugas'}</button><p>Instruksi skill disalin saat tugas dibuat. Mengedit skill setelahnya tidak mengubah tugas ini.</p></form>
 <section className={s.list}><h3>Tugas tersimpan · {jobs.length}</h3>{jobs.map(j=><button key={j.id} aria-pressed={selected===j.id} onClick={()=>{setSelected(j.id);setDetail(null);setError('');}}><span className={s.badge} data-state={j.status}>{j.status}{j.lease_expired?' · lease expired':''}</span><strong>{j.title}</strong><small>{j.target} · {j.owner||'belum diambil'} · {when(j.updated)}</small></button>)}{!jobs.length&&<p className={s.empty}>Belum ada tugas. Agent yang terhubung bisa mengambil tugas setelah lu membuat dan menugaskannya.</p>}</section></div>
 {error&&<p role="alert" className={s.error}>{error}</p>}
 {detail&&<section className={s.panel}><div className={s.heading}><div><span className={s.eyebrow}>{detail.id}</span><h2>{detail.title}</h2><p>{detail.status} · {detail.owner||'menunggu agent'}</p></div><div className={s.actions}>{['queued','running'].includes(detail.status)&&<button disabled={busy} onClick={cancel}>Batalkan tugas</button>}{detail.result&&<button onClick={()=>download(`${detail.id}.md`,detail.result)}>Download hasil</button>}</div></div><p className={s.notice}>Kirim instruksi ini ke agent yang sudah terhubung: <strong>“Baca tugas VRP {detail.id}, ambil jika tersedia, kerjakan, dan kirim hasilnya ke dashboard.”</strong></p><pre className={s.output}>{detail.prompt}</pre>{detail.skill_content&&<details><summary>Skill yang dipakai saat tugas dibuat</summary><pre className={s.output}>{detail.skill_content}</pre></details>}<h3>Hasil agent</h3><pre className={s.output}>{detail.result||'Belum ada hasil. Status completed berarti agent melaporkan selesai; tinjau bukti dan hasilnya.'}</pre><h3>Riwayat progres</h3>{detail.events?.map((e,i)=><article className={s.event} key={i}><span>{when(e.at)} · {e.status}</span><pre>{e.message}</pre></article>)}</section>}
 </>;
}
