'use client';
import { useState } from 'react';
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from 'recharts';
import { csv, num, useMacro } from './macroData';
import { HORIZONS, REACTION_ASSETS, ReactionData, ReactionRow } from './reactionData';
import s from './MacroDashboard.module.css';

export default function EventReaction({timezone}:{timezone:string}) {
  const [symbol,setSymbol]=useState('SPY'),[series,setSeries]=useState(''),[surprise,setSurprise]=useState('all'),[horizon,setHorizon]=useState(60),[band,setBand]=useState(.1),[event,setEvent]=useState(''),[force,setForce]=useState(false),[search,setSearch]=useState('');
  const params=new URLSearchParams({symbol,series_filter:series,surprise,horizon:String(horizon),band:String(band),refresh:String(force)});
  if(event)params.set('event_id',event);
  const result=useMacro<ReactionData>(`reactions?${params}`), d=result.data;
  function change(fn:()=>void){setEvent('');setForce(false);fn();}
  function refresh(){if(force)result.refresh();else setForce(true);}
  const selected=d?.rows.find(r=>r.id===d.selected_id), rows=d?.rows.filter(r=>`${r.title} ${r.source} ${r.date}`.toLowerCase().includes(search.toLowerCase()))||[];
  const points=d?.path.filter(p=>p.minute<=horizon)||[], scatter=d?.rows.filter(r=>r.score!=null&&r.returns[String(horizon)].value!=null).map(r=>({z:r.score,return:r.returns[String(horizon)].value,title:r.title,date:r.date}))||[];
  const overlaps=selected?.overlaps.filter(e=>Date.parse(e.date)-Date.parse(selected.date)<=horizon*60000)||[];
  const date=(v:string)=>v.length===10?v:new Date(v).toLocaleString('en-GB',{timeZone:timezone,dateStyle:'medium',timeStyle:'short'});
  const tone=(v:number|null)=>v==null?'':v>band?s.accent:v < -band?s.negative:'';
  function exportHistory(){csv(`${symbol}-macro-reactions.csv`,rows.map(r=>({title:r.title,release_time:r.date,source:r.source,source_url:r.url,actual:r.actual,consensus:r.forecast,consensus_z:r.score,baseline_price:r.baseline?.price,baseline_time:r.baseline?.sampled_at,baseline_captured_at:r.baseline?.captured_at,
    ...Object.fromEntries(HORIZONS.flatMap(h=>[[`return_${h.value}m_pct`,r.returns[String(h.value)].value],[`status_${h.value}m`,r.returns[String(h.value)].reason],[`sampled_${h.value}m`,r.returns[String(h.value)].sampled_at],[`captured_${h.value}m`,r.returns[String(h.value)].captured_at]])),
    label:r.label,label_horizon_minutes:horizon,small_reaction_pct:band,price_fetched_at:d?.price_source.fetched_at,price_stale:d?.price_source.stale,release_status:r.reaction_status})));}
  return <section aria-label="Macro Event Reaction">
    <div className={s.sectionHead}><div><span className={s.eyebrow}>RELEASE → PRICE RESPONSE</span><h2>Macro Event Reaction</h2><p>Ukur reaksi harga di sekitar berita USD. Pilih kejadian, replay jalurnya, lalu bandingkan dengan histori.</p></div><button onClick={refresh} disabled={result.loading}>Refresh harga</button></div>
    <div className={s.controls}>
      <label>Aset reaksi<select value={symbol} onChange={e=>change(()=>setSymbol(e.target.value))}>{REACTION_ASSETS.map(a=><option key={a.symbol} value={a.symbol}>{a.symbol} · {a.label}</option>)}</select></label>
      <label>Seri dan sumber rilis<select value={series} onChange={e=>change(()=>setSeries(e.target.value))}><option value="">Semua seri</option>{(d?.series||[series].filter(Boolean)).map(key=><option key={key} value={key}>{key.split('|')[1]} · {key.split('|')[0]}</option>)}</select></label>
      <label>Surprise konsensus<select value={surprise} onChange={e=>change(()=>setSurprise(e.target.value))}><option value="all">Semua surprise</option><option value="above">Di atas · Z &gt; 0.5</option><option value="neutral">Netral · |Z| ≤ 0.5</option><option value="below">Di bawah · Z &lt; −0.5</option><option value="unscored">Belum ada skor</option></select></label>
      <label>Horizon reaksi<select value={horizon} onChange={e=>change(()=>setHorizon(+e.target.value))}>{HORIZONS.map(h=><option key={h.value} value={h.value}>{h.label}</option>)}</select></label>
      <label>Batas reaksi kecil<select value={band} onChange={e=>change(()=>setBand(+e.target.value))}>{[.05,.1,.25,.5].map(v=><option key={v} value={v}>±{v}%</option>)}</select></label>
    </div>
    <p className={s.notice}>Bar 5 menit termasuk pre/post-market bila tersedia. +24 jam memakai waktu kalender, bukan sesi trading berikutnya. Label berlaku untuk <strong>{symbol}</strong>; gerak sesudah jadwal tidak membuktikan penyebabnya.</p>
    {result.loading&&<div role="status" className={s.skeleton}>Mengambil harga dan mencocokkan waktu rilis…</div>}
    {result.error&&<div role="alert" className={s.error}>{result.error}<button onClick={result.refresh}>Coba reaksi lagi</button></div>}
    {d&&<>
      <div className={s.statusStrip}><span>{d.price_source.provider} · 5m</span><span>{d.price_source.fetched_at?`Snapshot ${date(d.price_source.fetched_at)}`:'Belum ada snapshot harga'}</span><small>Timezone: {timezone} · cache 15 menit</small></div>
      <p className={s.footnote}>Cakupan harga tersimpan: {d.price_source.first_bar?date(d.price_source.first_bar):'—'} → {d.price_source.last_bar?date(d.price_source.last_bar):'—'}. Tanggal lama tanpa harga tetap tidak dinilai.</p>
      {d.price_source.error&&<div className={s.error} role="status"><strong>{d.price_source.fetched_at?'Refresh gagal · memakai cache':'Harga belum tersedia'}</strong><span>{d.price_source.error}</span><button onClick={refresh}>Coba harga lagi</button></div>}
      <div className={s.stats}><div><span>Timestamp unik · horizon terpilih</span><strong>{d.summary.n}</strong><small>{d.rows.length} source records; duplikat waktu dihitung sekali</small></div><div><span>Median return · {symbol}</span><strong className={tone(d.summary.median)}>{num(d.summary.median)}%</strong><small>Gabungan sesuai filter seri dan surprise</small></div><div><span>Reaksi kecil · ±{band}%</span><strong>{d.summary.small}</strong><small>Dari {d.summary.n} timestamp dengan harga lengkap</small></div><div><span>Posterior P(return &gt; 0)</span><strong>{d.summary.posterior?`${num(d.summary.posterior.mean*100,1)}%`:'—'}</strong><small>{d.summary.posterior?`80% interval: ${num(d.summary.posterior.lower*100,1)}–${num(d.summary.posterior.upper*100,1)}% · Beta(1,1) prior`:'Butuh ≥5 timestamp unik untuk estimasi'}</small></div></div>
      {selected?<>
        <div className={s.reactionFocus}><div><span className={s.eyebrow}>SELECTED EVENT / {symbol}</span><h3>{selected.title}</h3><p>{date(selected.date)} · {selected.source}</p><span className={`${s.modelBadge} ${labelTone(selected.label)}`}>{selected.label}</span><p>{selected.reaction_status}</p></div><div><span className={s.eyebrow}>ACTUAL / CONSENSUS / Z</span><strong>{selected.actual??'—'} / {selected.forecast??'—'} / {num(selected.score)} σ</strong><p>{selected.status}</p>{selected.url&&<a href={selected.url} target="_blank" rel="noreferrer">Buka sumber rilis ↗</a>}</div></div>
        <div className={s.reactionReturns}>{HORIZONS.map(h=>{const r=selected.returns[String(h.value)];return <div key={h.value}><span className={s.eyebrow}>{h.label}</span><strong className={tone(r.value)}>{num(r.value)}{r.value!=null?'%':''}</strong><small>{r.reason||`Harga pada ${date(r.sampled_at!)} · lag ${num(r.lag_seconds,0)}s`}</small></div>})}</div>
        <div className={s.chartBox}><div className={s.sectionHead}><div><h3>Event replay · {symbol}</h3><p>t=0: {date(selected.date)}. Baseline {selected.baseline?`${num(selected.baseline.price,3)} pada ${date(selected.baseline.sampled_at)} (lag ${selected.baseline.lag_seconds}s)`:'tidak tersedia'}.</p></div></div>
          {points.some(p=>p.value!=null)?<div className={s.chart}><ResponsiveContainer width="100%" height="100%"><LineChart data={points}><CartesianGrid stroke="#25303c" vertical={false}/><XAxis dataKey="minute" type="number" domain={[-30,horizon]} tick={{fill:'#a1afbe',fontSize:11}} tickFormatter={v=>`${v>0?'+':''}${v}m`}/><YAxis tick={{fill:'#a1afbe',fontSize:11}} width={58} tickFormatter={v=>`${num(v)}%`} domain={['auto','auto']}/><Tooltip contentStyle={{background:'#111b27',borderColor:'#354353'}} labelFormatter={v=>`t ${Number(v)>0?'+':''}${v} menit`} formatter={(v:number)=>[`${num(v,3)}%`,'Return dari baseline']}/><ReferenceLine x={0} stroke="#efb353" label={{value:'Rilis',fill:'#efb353'}}/><ReferenceLine y={0} stroke="#748397"/><Line dataKey="value" stroke="#54d5cb" dot={false} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>:<p className={s.empty}>Replay belum tersedia. Periksa waktu rilis, cakupan intraday, dan harga sebelum rilis.</p>}
        </div>
        <details className={s.method}><summary>{overlaps.length} source records lain dalam jendela {horizon} menit</summary><p>Termasuk rilis simultan dan kemungkinan laporan duplikat. Kejadian di luar kalender yang dikumpulkan tetap bisa memengaruhi harga.</p>{overlaps.slice(0,30).map(e=><p key={e.id}>{date(e.date)} · {e.title} · {e.source}</p>)}{overlaps.length>30&&<p>Menampilkan 30 dari {overlaps.length} records.</p>}</details>
      </>:<p className={s.empty}>Belum ada rilis yang cocok. Ubah filter atau refresh kalender ECO untuk mengumpulkan jadwal.</p>}
      <div className={`${s.sectionHead} ${s.reactionHistoryHead}`}><div><h3>Histori reaksi</h3><p>Pilih baris untuk replay. Tanggal tanpa jam dan harga yang hilang tetap terlihat.</p></div><button onClick={exportHistory} disabled={!rows.length}>Export reaksi CSV</button></div>
      <label className={s.reactionSearch}>Cari histori reaksi<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="CPI, payrolls, tanggal, sumber…"/></label>
      <div className={s.tableMeta}><span>{rows.length} records ditampilkan · statistik mengikuti filter di atas</span><span>Return harga (%) · tanpa biaya trading</span></div>
      <div className={`${s.tableScroll} ${s.reactionTable}`} tabIndex={0} aria-label="Tabel histori reaksi"><table className={s.table}><thead><tr><th>Rilis / waktu</th><th>Actual / consensus</th><th>Surprise Z</th>{HORIZONS.map(h=><th key={h.value}>{h.label}</th>)}<th>Reaksi · {horizon}m</th></tr></thead><tbody>{rows.map(r=><ReactionHistoryRow key={r.id} row={r} selected={r.id===d.selected_id} band={band} date={date} onSelect={()=>setEvent(r.id)}/>)}</tbody></table>{!rows.length&&<p className={s.empty}>Tidak ada histori yang cocok dengan pencarian.</p>}</div>
      <div className={`${s.chartBox} ${s.reactionHistoryHead}`}><h3>Surprise konsensus vs return · {horizon}m</h3><p>Sumbu X: surprise Z; sumbu Y: return {symbol}. Pilih satu seri/sumber agar definisi surprise konsisten.</p>{scatter.length?<div className={s.chart}><ResponsiveContainer width="100%" height="100%"><ScatterChart><CartesianGrid stroke="#25303c"/><XAxis type="number" dataKey="z" name="Surprise Z" tick={{fill:'#a1afbe',fontSize:11}}/><YAxis type="number" dataKey="return" name="Return" unit="%" tick={{fill:'#a1afbe',fontSize:11}}/><ReferenceLine x={0} stroke="#748397"/><ReferenceLine y={0} stroke="#748397"/><Tooltip cursor={{strokeDasharray:'3 3'}} contentStyle={{background:'#111b27',borderColor:'#354353'}}/><Scatter data={scatter} fill="#efb353" isAnimationActive={false}/></ScatterChart></ResponsiveContainer></div>:<p className={s.empty}>Belum ada pasangan skor konsensus dan return. Histori harga tetap bisa dibaca; actual/consensus bisa ditambah lewat impor bersumber di Surprise Monitor.</p>}</div>
      <details className={s.method}><summary>Metode, cakupan, dan cara membaca</summary><p>Baseline adalah close bar 5 menit yang selesai paling akhir pada/sebelum timestamp rilis, dengan lag kurang dari 5 menit. Setiap horizon memakai aturan sama, hanya setelah horizon selesai. Return = (harga horizon / baseline − 1) × 100. Tidak memakai close bar yang masih berjalan, mengisi gap pasar tutup, atau mengganti intraday dengan close harian.</p><p>Naik/turun bertahan berarti return 5 menit dan horizon terpilih searah serta keduanya di luar batas reaksi kecil. Reversal berarti tandanya berlawanan dan keduanya melewati batas. Batas adalah aturan persen yang lu pilih, bukan ukuran shock statistik.</p><p>Yahoo diminta untuk 59 hari terakhir; cakupan aktual bisa lebih pendek. Harga yang sudah ditangkap dipertahankan hingga 200.000 bar per aset; timestamp pengambilan per harga ikut diekspor. Cache harga diperbarui tiap 15 menit; refresh manual minimal 60 detik. Return memakai harga provider tanpa auto-adjust tambahan, bukan total return. Stock split yang dilaporkan dalam jendela membuat return tidak dinilai. GLD/UUP adalah ETF proxy, bukan spot gold atau DXY.</p><p>Surprise memakai actual/consensus yang ditangkap, bukan forecast FRED periode referensi. Record yang hanya punya jadwal tetap ditandai belum terverifikasi. Rilis yang tersedia bisa mengandung revisi dan bukan vintage-correct. Timestamp yang sama dihitung sekali dalam statistik; jendela yang tumpang tindih masih dapat saling bergantung.</p><p>Posterior memakai prior Beta(1,1), diperbarui dengan jumlah return positif dan nonpositif. Interval 80% bersifat deskriptif dengan asumsi observasi independen dan kondisi stabil; bukan probabilitas trading terkalibrasi. Filter semua seri menggabungkan kejadian yang heterogen. Pencarian tabel hanya menyaring tampilan dan ekspor.</p></details>
    </>}
  </section>;
}

function ReactionHistoryRow({row:r,selected,band,date,onSelect}:{row:ReactionRow;selected:boolean;band:number;date:(v:string)=>string;onSelect:()=>void}) {
  return <tr data-selected={selected}><td><button className={s.eventButton} aria-pressed={selected} onClick={onSelect}>{r.title}</button><small>{date(r.date)} · {r.precision==='date'?'Jam tidak diketahui':r.source}</small></td><td>{r.actual??'—'} / {r.forecast??'—'}</td><td className={s.number}>{num(r.score)}<small>{r.classification}</small></td>{HORIZONS.map(h=>{const v=r.returns[String(h.value)];return <td key={h.value} className={`${s.number} ${v.value!=null&&v.value>band?s.accent:v.value!=null&&v.value< -band?s.negative:''}`} title={v.reason||v.sampled_at||''}>{num(v.value)}{v.value!=null?'%':''}<small>{v.reason}</small></td>})}<td><span className={`${s.modelBadge} ${labelTone(r.label)}`}>{r.label}</span><small>{r.reaction_status}</small></td></tr>;
}

function labelTone(label:string){return label.toLowerCase().includes('naik')?s.modelBull:label.toLowerCase().includes('turun')?s.modelBear:s.modelNeutral;}
