'use client';
import { useMemo, useState } from 'react';
import { BarChart, Bar, Cell, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ModelResult, csv, num, useMacro } from './macroData';
import { defaultUsdDirection, modelLabel } from './modelSurprise';
import s from './MacroDashboard.module.css';

interface Snapshot { generated_at:string;target_period:string;mean:number;lower:number;upper:number;source_fetched_at:string|null;source_stale:boolean;window:number;strength:number;input_hash:string }
export default function ModelSurpriseHistory({ data:d }: { data:ModelResult }) {
  const [direction,setDirection]=useState(defaultUsdDirection(d.key)),[neutral,setNeutral]=useState(.5),[shock,setShock]=useState(2),[filter,setFilter]=useState('Semua'),[view,setView]=useState('evaluated');
  const saved=useMacro<Snapshot[]>(view==='saved'?`forecast-history?series=${d.key}`:null);
  const all=useMemo(()=>[...d.evaluation].reverse().map(r=>({...r,...modelLabel(r.model_z,direction,neutral,shock)})),[d.evaluation,direction,neutral,shock]);
  const rows=all.filter(r=>filter==='Semua'||filter==='Netral'&&r.tone==='neutral'||filter==='Bullish'&&r.tone==='bull'||filter==='Bearish'&&r.tone==='bear'||filter==='Shock'&&r.label.includes('shock'));
  const latest=all[0], bull=all.filter(r=>r.tone==='bull').length,bear=all.filter(r=>r.tone==='bear').length,flat=all.filter(r=>r.tone==='neutral').length;
  const plot=[...rows].slice(0,24).reverse();
  function exportRows(){csv(`${d.key}-model-surprise.csv`,rows.map(r=>({...r,series:d.series,unit:d.unit,usd_direction:direction,neutral_band:neutral,shock_threshold:shock,data_basis:'latest revised / reconstructed',input_hash:d.input_hash})));}
  return <section className={s.modelHistory} aria-label="Model surprise history">
    <div className={s.sectionHead}><div><span className={s.eyebrow}>ACTUAL VS MODEL SENDIRI / SKENARIO USD</span><h3>Histori surprise model</h3><p>Lihat periode mana yang netral, bullish, bearish, atau menghasilkan shock besar terhadap perkiraan model.</p></div><button disabled={!rows.length} onClick={exportRows}>Export histori model</button></div>
    <div className={s.controls}>
      <label>Asumsi arah USD<select value={direction} onChange={e=>setDirection(Number(e.target.value) as 1|-1)}><option value={1}>Actual lebih tinggi → bullish USD</option><option value={-1}>Actual lebih tinggi → bearish USD</option></select></label>
      <label>Batas netral model<select value={neutral} onChange={e=>setNeutral(+e.target.value)}>{[.25,.5,1].map(v=><option key={v} value={v}>±{v} σ</option>)}</select></label>
      <label>Batas shock model<select value={shock} onChange={e=>setShock(+e.target.value)}>{[1.5,2,3].map(v=><option key={v} value={v}>≥ {v} σ</option>)}</select></label>
      <label>Filter label model<select value={filter} onChange={e=>setFilter(e.target.value)}>{['Semua','Netral','Bullish','Bearish','Shock'].map(v=><option key={v}>{v}</option>)}</select></label>
    </div>
    <p className={s.notice}><strong>Acuan: USD, bukan SPY.</strong> Bull/bear adalah interpretasi berdasarkan aturan yang lu pilih, bukan return pasar yang terukur. Actual di sini merupakan observasi FRED yang sudah direvisi. Histori ini direkonstruksi per periode, bukan rekaman forecast yang diterbitkan saat itu.</p>
    <div className={s.stats}><div><span>Periode terbaru · {latest?.period || '—'}</span><strong className={latest?.tone==='bull'?s.accent:latest?.tone==='bear'?s.negative:undefined}>{latest?.label || 'Belum dinilai'}</strong><small>{latest?.reason}</small></div><div><span>Bullish USD</span><strong className={s.accent}>{bull}</strong><small>Jumlah periode dalam skenario ini</small></div><div><span>Netral</span><strong>{flat}</strong><small>Dalam rentang ±{neutral}σ</small></div><div><span>Bearish USD</span><strong className={s.negative}>{bear}</strong><small>Jumlah periode dalam skenario ini</small></div></div>
    <div className={s.sectionHead}><div className={s.segment}><button aria-pressed={view==='evaluated'} onClick={()=>setView('evaluated')}>Histori evaluasi</button><button aria-pressed={view==='saved'} onClick={()=>setView('saved')}>Forecast tersimpan</button></div></div>
    {view==='evaluated'?<>
      {plot.length>0&&<div className={s.chartBox}><p>Model Z = (actual − forecast model) / simpangan baku prediktif sebelum actual. Warna mengikuti skenario USD; tinggi bar menunjukkan deviasi ekonomi.</p><div className={s.chart}><ResponsiveContainer width="100%" height="100%"><BarChart data={plot}><CartesianGrid stroke="#25303c" vertical={false}/><XAxis dataKey="period" tick={{fill:'#a1afbe',fontSize:10}} minTickGap={35}/><YAxis width={45} tick={{fill:'#a1afbe',fontSize:10}}/><Tooltip contentStyle={{background:'#111b27',borderColor:'#354353'}} formatter={(v:number)=>num(v)}/><ReferenceLine y={0} stroke="#a1afbe"/>{[neutral,-neutral].map(v=><ReferenceLine key={v} y={v} stroke="#efb353" strokeDasharray="4 4"/>)}<Bar dataKey="model_z" name="Model Z" isAnimationActive={false}>{plot.map(r=><Cell key={r.period} fill={r.tone==='bull'?'#54d5cb':r.tone==='bear'?'#f5b38d':'#a1afbe'}/>)}</Bar></BarChart></ResponsiveContainer></div></div>}
      <div className={s.tableMeta}><span>{rows.length} periode · {d.unit}</span><span>Terbaru dahulu · bukan surprise konsensus</span></div>
      <div className={s.tableScroll}><table className={s.table}><thead><tr><th>Periode</th><th>Actual revisi</th><th>Forecast model</th><th>Selisih / Model Z</th><th>Label skenario USD</th></tr></thead><tbody>{rows.map(r=><tr key={r.period}><td>{r.period}</td><td className={s.number}>{num(r.actual,3)}</td><td className={s.number}>{num(r.model,3)}<small>80%: {num(r.lower)} – {num(r.upper)}</small></td><td className={s.number}>{num(r.surprise ?? r.actual-r.model,3)}<small>{num(r.model_z)} σ</small></td><td><span className={`${s.modelBadge} ${r.tone==='bull'?s.modelBull:r.tone==='bear'?s.modelBear:s.modelNeutral}`}>{r.label}</span><small>{r.reason}</small></td></tr>)}</tbody></table></div>
      {!rows.length&&<div className={s.empty}>Tidak ada periode yang cocok dengan filter ini.</div>}
    </>:<>
      <p className={s.footnote}>Ini forecast yang benar-benar pernah disimpan aplikasi, termasuk pengaturannya. Waktu simpan bukan bukti bahwa forecast mendahului rilis resmi. Forecast tersimpan tidak diganti dengan prediksi rekonstruksi.</p>
      {saved.loading&&<p role="status">Membaca forecast tersimpan…</p>}{saved.error&&<div role="alert" className={s.error}>{saved.error}<button onClick={saved.refresh}>Coba lagi</button></div>}
      {saved.data&&<div className={s.tableScroll}><table className={s.table}><thead><tr><th>Disimpan</th><th>Target periode</th><th>Forecast / interval 80%</th><th>Pengaturan</th><th>Snapshot sumber</th></tr></thead><tbody>{saved.data.map((r,i)=><tr key={`${r.generated_at}-${i}`}><td>{new Date(r.generated_at).toLocaleString()}</td><td>{r.target_period}</td><td>{num(r.mean,3)}<small>{num(r.lower)} – {num(r.upper)}</small></td><td>{r.window} observasi · prior {r.strength}</td><td>{r.source_fetched_at?new Date(r.source_fetched_at).toLocaleString():'Tidak diketahui'}<small>{r.source_stale?'Cache saat refresh gagal':'Snapshot berhasil diambil'}</small></td></tr>)}</tbody></table>{!saved.data.length&&<p className={s.empty}>Belum ada forecast tersimpan untuk seri ini.</p>}</div>}
    </>}
    <details className={s.method}><summary>Cara membaca label dan skor</summary><p>Netral: |Z| ≤ {neutral}. Di luar itu, tanda surprise dikalikan arah USD yang dipilih untuk menentukan bullish/bearish. Shock: |Z| ≥ {shock}. Ambang ini aturan deskriptif yang bisa diedit; bukan probabilitas menang.</p><p>Simpangan baku prediktif berasal dari distribusi Student-t model pada setiap titik evaluasi: scale × √(df/(df−2)). Forecast dan skalanya memakai data sebelum periode actual. Revisi historis tetap membuat ini berbeda dari backtest berbasis data yang tersedia pada waktu rilis.</p><p>Default: kenaikan claims/unemployment diberi arah USD negatif; seri lain positif melalui asumsi pertumbuhan/kebijakan suku bunga. Hubungan itu dapat berubah menurut kondisi pasar. Label berlaku untuk surprise terhadap model internal; tidak mengukur surprise terhadap konsensus ekonom.</p></details>
  </section>;
}
