'use client';
import { useMemo, useState } from 'react';
import { BarChart, Bar, Cell, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { csv, day, num, useMacro } from './macroData';
import s from './MacroDashboard.module.css';

interface Release {
  id: string; title: string; date: string; source: string; url: string | null; actual: string | null; forecast: string | null;
  score: number | null; centered_z: number | null; surprise: number | null; surprise_unit: string | null;
  classification: string; magnitude: string | null; status: string; history_n: number; history_mean: number | null; history_sd: number | null; provenance: string; captured_at: string;
}
interface Scores { rows: Release[]; scored: number; paired: number; min_history: number; vintage: string }
interface Preview { count: number; saved: boolean; preview: { title: string; date: string; actual: string; forecast: string; unit: string }[] }

function ImportHistory({ done }: { done: () => void }) {
  const [text, setText] = useState(''), [preview, setPreview] = useState<Preview | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('');
  async function submit(save: boolean) {
    setBusy(true); setError(''); setMessage('');
    try {
      const response = await fetch('/api/macro/surprises/import', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ csv_text: text, save }) });
      const body = await response.json(); if (!response.ok) throw new Error(typeof body.detail === 'string' ? body.detail : 'CSV validation failed');
      if (save) { setMessage(`${body.count} released observations saved. Imported data remains separate from provider snapshots.`); setPreview(null); done(); } else setPreview(body);
    } catch (e) { setError(e instanceof Error ? e.message : 'Import failed'); } finally { setBusy(false); }
  }
  return <details className={s.method}><summary>Import actual / consensus history</summary>
    <p>Import your sourced USD High-impact history to build a baseline. Keep one stable series name per definition: core/headline, m/m/y/y and GDP estimate vintage must stay separate. Imported rows are labelled user-supplied and are not independently verified.</p>
    <p>CSV columns: <code>series,date,actual,forecast,unit,source_url</code>. Use ISO release timestamps with an offset. Units: percent, thousands, count, index, number or bps. Percentage values use percentage points (0.3 for 0.3%). Maximum 1000 rows / 1 MB. Preview validates every row before saving.</p>
    <label>History CSV file<input type="file" accept=".csv,text/csv" disabled={busy} onChange={async e => { const file = e.target.files?.[0]; setPreview(null); setMessage(''); setText(''); if (!file) return; if (file.size > 1_000_000) { setError('File exceeds 1 MB'); return; } try { setText(await file.text()); setError(''); } catch { setError('Could not read file'); } }} /></label>
    <div className={s.controls} style={{ marginTop: 12 }}><button disabled={!text || busy} onClick={() => submit(false)}>Preview CSV</button><button disabled={!preview || busy} onClick={() => submit(true)}>Save imported releases</button><span>{busy ? 'Validating…' : preview ? `${preview.count} valid rows · preview below` : 'No data is saved until you choose Save'}</span></div>
    {error && <p role="alert" className={s.error}>{error}</p>}{message && <p role="status">{message}</p>}
    {preview && <div className={s.tableScroll}><table className={s.table}><thead><tr><th>Series</th><th>Release date</th><th>Actual</th><th>Consensus</th><th>Unit</th></tr></thead><tbody>{preview.preview.map((r,i) => <tr key={i}><td>{r.title}</td><td>{r.date}</td><td>{r.actual}</td><td>{r.forecast}</td><td>{r.unit}</td></tr>)}</tbody></table></div>}
  </details>;
}

export default function SurprisePanel({ timezone }: { timezone: string }) {
  const [window, setWindow] = useState(36), [neutral, setNeutral] = useState(.5), [query, setQuery] = useState(''), [filter, setFilter] = useState('All'), [selected, setSelected] = useState<string | null>(null);
  const result = useMacro<Scores>(`surprises?window=${window}&neutral=${neutral}`);
  const rows = useMemo(() => (result.data?.rows || []).filter(r => r.title.toLowerCase().includes(query.toLowerCase()) && (filter === 'All' || filter === 'Scored' ? filter === 'All' || r.score != null : r.classification === filter)), [result.data, query, filter]);
  const focus = result.data?.rows.find(r => r.id === selected);
  const plotted = rows.filter(r => r.score != null).slice(0, 24).reverse().map(r => ({ ...r, display: `${day(r.date,timezone)} · ${r.title}` }));
  return <section>
    <div className={s.sectionHead}><div><span className={s.eyebrow}>USD HIGH IMPACT / RELEASED ACTUALS</span><h2>Surprise Monitor</h2><p>Measure how far the actual print deviates from consensus, relative to that release&apos;s own historical forecast errors.</p></div><div className={s.segment}><button onClick={result.refresh} disabled={result.loading}>Refresh scores</button><button disabled={!rows.length} onClick={() => csv('usd-surprise-scores.csv',rows.map(r => ({...r})))}>Export scores</button></div></div>
    <div className={s.controls}><label>Surprise lookback<select value={window} onChange={e => setWindow(+e.target.value)}>{[12,24,36,60].map(n => <option key={n} value={n}>{n} prior releases</option>)}</select></label><label>Neutral band<select value={neutral} onChange={e => setNeutral(+e.target.value)}>{[.25,.5,1].map(n => <option key={n} value={n}>±{n} σ</option>)}</select></label><label>Score filter<select value={filter} onChange={e => setFilter(e.target.value)}>{['All','Scored','Above expectations','Neutral','Below expectations'].map(f => <option key={f}>{f}</option>)}</select></label><label className={s.search}>Search surprise releases<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Core CPI m/m, payrolls…" /></label></div>
    <p className={s.notice}>Surprise Z = (actual − consensus) / SD of prior surprises. Neutral means |Z| ≤ {neutral}; it does not mean “no market impact”. Missing data or fewer than 12 prior pairs stays unscored. This is a descriptive analysis of captured/imported values, not a first-release backtest.</p>
    {result.loading && <div className={s.skeleton} role="status">Calculating release surprises…</div>}{result.error && <div className={s.error} role="alert">{result.error}<button onClick={result.refresh}>Retry scores</button></div>}
    {result.data && <>
      <div className={s.stats}><div><span>Actual + consensus pairs</span><strong>{result.data.paired}</strong><small>Released, compatible units</small></div><div><span>Scored releases</span><strong>{result.data.scored}</strong><small>At least 12 prior pairs and nonzero variance</small></div><div><span>Neutral band</span><strong>±{neutral} σ</strong><small>Configurable descriptive threshold</small></div><div><span>Historical baseline</span><strong>{window}</strong><small>Prior releases · same definition, source and unit</small></div></div>
      {!result.data.scored && <div className={s.empty}>No scoreable history yet. Existing feeds may omit actual or consensus. Import sourced historical pairs below; Z-scores begin at the 13th valid release of each series. Actual and raw surprise remain visible when available.</div>}
      {plotted.length>0 && <div className={s.chartBox}><div className={s.sectionHead}><div><h3>Recent standardized surprises</h3><p>Most recent 24 scored rows in this filter. Positive = above consensus, negative = below; bars do not show market returns.</p></div></div><div className={s.chart}><ResponsiveContainer width="100%" height="100%"><BarChart data={plotted}><CartesianGrid stroke="#25303c" vertical={false} /><XAxis dataKey="display" tick={false} /><YAxis tick={{fill:'#aab7c6',fontSize:11}} width={48} /><Tooltip contentStyle={{background:'#111b27',borderColor:'#354353',color:'#edf2f7'}} formatter={(v:number)=>num(v)} /><ReferenceLine y={0} stroke="#a1afbe" /><ReferenceLine y={neutral} stroke="#efb353" strokeDasharray="4 4" /><ReferenceLine y={-neutral} stroke="#efb353" strokeDasharray="4 4" /><Bar dataKey="score" name="Surprise Z" isAnimationActive={false}>{plotted.map(r=><Cell key={r.id} fill={r.classification==='Neutral'?'#a1afbe':r.score!>0?'#54d5cb':'#f5b38d'} />)}</Bar></BarChart></ResponsiveContainer></div></div>}
      <div className={s.tableMeta}><span>{rows.length} matching source records · latest 150 shown</span><span>Positive ≠ bullish · Negative ≠ bearish</span></div>
      <div className={s.tableScroll}><table className={s.table}><thead><tr><th>Date / release</th><th>Actual / consensus</th><th>Raw surprise</th><th>Surprise Z</th><th>Classification</th><th>Prior samples</th></tr></thead><tbody>{rows.slice(0,150).map(r=><tr key={r.id}><td><button className={s.eventButton} onClick={()=>setSelected(r.id)}>{r.title}</button><small>{day(r.date,timezone)} · {r.source}</small></td><td className={s.number}>{r.actual ?? '—'} / {r.forecast ?? '—'}</td><td className={s.number}>{num(r.surprise)}<small>{r.surprise_unit || ''}</small></td><td className={s.number}>{num(r.score)}</td><td><strong className={r.classification==='Above expectations'?s.accent:r.classification==='Below expectations'?s.negative:undefined}>{r.classification}</strong><small>{r.magnitude || r.status}</small></td><td className={s.number}>{r.history_n}</td></tr>)}</tbody></table></div>
      {!rows.length && <div className={s.empty}>No released observations match this filter.</div>}
      {focus && <aside className={s.detail}><div className={s.sectionHead}><div><span className={s.eyebrow}>RELEASE DIAGNOSTICS</span><h3>{focus.title}</h3></div><button onClick={()=>setSelected(null)}>Close diagnostics</button></div><div className={s.stats}><div><span>Surprise Z</span><strong>{num(focus.score)}</strong><small>{focus.classification}</small></div><div><span>Bias-adjusted Z</span><strong>{num(focus.centered_z)}</strong><small>(surprise − historical mean) / SD</small></div><div><span>Prior surprise mean</span><strong>{num(focus.history_mean)}</strong><small>{focus.surprise_unit} · forecast bias</small></div><div><span>Prior surprise SD</span><strong>{num(focus.history_sd)}</strong><small>{focus.history_n} prior observations</small></div></div><p>{focus.status}. {focus.provenance}. Captured {focus.captured_at}.</p><p>Interpret the release definition: higher inflation is a hotter print; higher claims signal more claims, not stronger employment. Market direction requires separate evidence from rates, positioning and observed price reaction.</p>{focus.url && <a href={focus.url} target="_blank" rel="noreferrer">Open source ↗</a>}</aside>}
    </>}
    <ImportHistory done={result.refresh} />
    <details className={s.method}><summary>Scoring methodology & limits</summary><p>The denominator is the sample standard deviation (n−1) of earlier actual-minus-consensus surprises in the same source, exact series definition and unit bucket. The current release and all later releases are excluded. Never use standard deviation of actual levels or replace consensus with previous.</p><p>Neutral: |Z| ≤ the selected band. Outside that band: modest below 1σ, large from 1σ to below 2σ, extreme from 2σ. These are descriptive cutoffs, not p-values, posterior probabilities or estimates of market return. Bias-adjusted Z is shown separately and does not determine the headline classification.</p><p>Snapshots may contain revised actuals or consensus captured after release. Imports are user-supplied. This prevents chronological holdout leakage but does not establish historical first-release or pre-release consensus vintages. Different data providers are not pooled.</p></details>
  </section>;
}
