'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { createChart, ColorType, CrosshairMode, HistogramSeries } from 'lightweight-charts';
import type { IChartApi, ISeriesApi, Time, UTCTimestamp, WhitespaceData, DeepPartial } from 'lightweight-charts';
import { Download, Expand, Settings2, RotateCcw, Layers3, Minus, Plus } from 'lucide-react';
import { Instrument } from '../../../lib/chart-studio/types';
import { useOrderFlow } from '../../../lib/chart-studio/useOrderFlow';
import { aggregateFootprint, footprintCsv, suggestedStep } from '../../../lib/chart-studio/footprint';
import { FootprintSeries, FootprintPoint, FootprintOptions, compactVolume } from '../../../lib/chart-studio/footprintSeries';
import './footprint.css';
const clock=(s:number)=>new Date(s*1000).toLocaleTimeString('en-GB',{timeZone:'UTC',hour12:false});
const price=(n:number)=>n.toLocaleString('en-US',{maximumFractionDigits:10});
export default function FootprintPanel({instrument,light,replay,interval,onIntervalChange}:{instrument:Instrument;light:boolean;replay:boolean;interval:number;onIntervalChange:(seconds:number)=>void}) {
  const [stepInput,setStepInput]=useState(''),[ratio,setRatio]=useState(3),[minimum,setMinimum]=useState(0),[units,setUnits]=useState<'base'|'quote'>('base');
  const [mode,setMode]=useState<'bidask'|'delta'>('bidask'),[showPoc,setShowPoc]=useState(true),[settings,setSettings]=useState(false),[reset,setReset]=useState(0),[selected,setSelected]=useState<number|null>(null),[follow,setFollow]=useState(true);
  const [buyColor,setBuyColor]=useState('#4bd6b0'),[sellColor,setSellColor]=useState('#f0808c'),[fontSize,setFontSize]=useState(11),[note,setNote]=useState('');
  const available=instrument.provider==='hyperliquid'&&!replay;
  const feed=useOrderFlow(instrument.symbol,available,reset);
  const auto=useRef<number|null>(null);if(auto.current==null&&feed.trades.length)auto.current=suggestedStep(feed.trades[0].price);
  const requested=stepInput===''?auto.current||1:Number(stepInput),validStep=Number.isFinite(requested)&&requested>0;
  const result=useMemo(()=>aggregateFootprint(available?feed.trades:[],{interval,step:validStep?requested:auto.current||1,ratio,minimum,stack:3,units}),[available,feed.trades,interval,requested,validStep,ratio,minimum,units]);
  const focused=result.bars.find(b=>b.time===selected)||result.bars.at(-1);
  const host=useRef<HTMLDivElement>(null),panel=useRef<HTMLElement>(null);
  const api=useRef<IChartApi|null>(null),series=useRef<ISeriesApi<'Custom',Time,FootprintPoint|WhitespaceData<Time>,FootprintOptions,DeepPartial<FootprintOptions>>|null>(null),delta=useRef<ISeriesApi<'Histogram'>|null>(null);
  const fitted=useRef(false);const [mounted,setMounted]=useState(false);
  useEffect(()=>{
    if(!host.current)return;
    const chart=createChart(host.current,{autoSize:true,layout:{background:{type:ColorType.Solid,color:'#0c121b'},textColor:'#8c9db4',fontFamily:'ui-monospace, monospace',fontSize:11,attributionLogo:true},grid:{vertLines:{color:'#1b2533'},horzLines:{color:'#1b2533'}},rightPriceScale:{borderColor:'#263449',scaleMargins:{top:.1,bottom:.1}},timeScale:{timeVisible:true,secondsVisible:false,barSpacing:120,minBarSpacing:8,rightOffset:2,borderColor:'#263449'},crosshair:{mode:CrosshairMode.Normal},localization:{locale:'en-US'},handleScale:{axisPressedMouseMove:true,mouseWheel:true,pinch:true}});
    const fp=chart.addCustomSeries(new FootprintSeries());const d=chart.addSeries(HistogramSeries,{priceLineVisible:false,lastValueVisible:false,priceFormat:{type:'volume'}},1);chart.panes()[1].setHeight(72);
    chart.subscribeCrosshairMove(e=>{if(e.time!=null&&typeof e.time==='number')setSelected(e.time);});
    api.current=chart;series.current=fp;delta.current=d;setMounted(true);
    return()=>{chart.remove();api.current=null;series.current=null;delta.current=null;};
  },[]);
  useEffect(()=>{fitted.current=false;setSelected(null);},[interval,reset]);
  useEffect(()=>{
    if(!series.current||!api.current||!delta.current)return;
    series.current.setData(result.bars.map(b=>({time:b.time as UTCTimestamp,footprint:b})));
    delta.current.setData(result.bars.map(b=>({time:b.time as UTCTimestamp,value:b.delta,color:b.delta>=0?buyColor:sellColor})));
    const precision=Math.min(10,Math.max(0,Math.ceil(-Math.log10(result.step))+1));series.current.applyOptions({priceFormat:{type:'price',precision,minMove:10**-precision}});
    if(result.bars.length&&!fitted.current){api.current.timeScale().setVisibleLogicalRange({from:Math.max(-1,result.bars.length-7),to:result.bars.length+1});fitted.current=true;}
    else if(follow&&result.bars.length)api.current.timeScale().scrollToRealTime();
  },[result,mounted,follow,buyColor,sellColor]);
  useEffect(()=>{series.current?.applyOptions({buyColor,sellColor,mode,showPoc,fontSize,textColor:light?'#1b293b':'#e7edf7'});api.current?.applyOptions({layout:{background:{type:ColorType.Solid,color:light?'#ffffff':'#0c121b'},textColor:light?'#526079':'#8c9db4'},grid:{vertLines:{color:light?'#e7edf3':'#1b2533'},horzLines:{color:light?'#e7edf3':'#1b2533'}}});},[mode,showPoc,buyColor,sellColor,fontSize,light,mounted]);
  function zoom(factor:number){const chart=api.current;if(chart)chart.timeScale().applyOptions({barSpacing:Math.max(8,Math.min(260,chart.timeScale().options().barSpacing*factor))});}
  function exportCsv(){const url=URL.createObjectURL(new Blob([footprintCsv(result.bars)],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`${instrument.symbol.replace(/[^\w-]/g,'_')}-footprint-${units}.csv`;a.click();URL.revokeObjectURL(url);}
  function exportPng(){try{const a=document.createElement('a');a.href=api.current!.takeScreenshot().toDataURL('image/png');a.download='footprint.png';a.click();}catch{setNote('Image export unavailable. Try again after the chart loads.');}}
  return <section ref={panel} className="fp-panel" style={{'--fp-buy':buyColor,'--fp-sell':sellColor} as React.CSSProperties} aria-label="Footprint chart">
    <div className="fp-heading"><div className="fp-title"><Layers3 size={20}/><div><h2>Footprint<span>{instrument.symbol}</span></h2><p>Executed volume at price · Hyperliquid</p></div></div><div className="fp-tools"><button onClick={()=>setSettings(v=>!v)} aria-pressed={settings} aria-label="Footprint settings"><Settings2 size={15}/>Settings</button><button onClick={exportPng} disabled={!result.bars.length} aria-label="Export footprint PNG"><Download size={15}/>PNG</button><button aria-label="Fullscreen footprint" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void panel.current?.requestFullscreen().catch(()=>setNote('Fullscreen unavailable'));}}><Expand size={16}/></button></div></div>
    <div className="fp-controls"><div className="fp-segments">{[60,300,900].map(n=><button key={n} aria-pressed={interval===n} onClick={()=>onIntervalChange(n)}>{n/60}m</button>)}</div><label>View<select aria-label="Footprint view" value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="bidask">Bid × Ask</option><option value="delta">Delta</option></select></label><label>Price / row<input aria-label="Footprint price per row" placeholder={`Auto ${price(auto.current||1)}`} value={stepInput} onChange={e=>setStepInput(e.target.value)} type="number" min="0" step="any" aria-invalid={!validStep}/></label><button aria-pressed={follow} onClick={()=>setFollow(v=>!v)} title="Disable Follow to browse older captured bars">{follow?'Following latest':'Browse history'}</button><span className="fp-feed" role="status">{available?feed.status:replay?'Replay paused':'Hyperliquid required'}</span></div>
    {settings&&<div className="fp-settings"><label>Imbalance<select aria-label="Footprint imbalance ratio" value={ratio} onChange={e=>setRatio(Number(e.target.value))}>{[2,3,4,5].map(n=><option value={n} key={n}>{n*100}% diagonal</option>)}</select></label><label>Minimum side volume<input aria-label="Footprint minimum side volume" type="number" min="0" step="any" value={minimum} onChange={e=>setMinimum(Math.max(0,Number(e.target.value)||0))}/></label><label>Volume units<select aria-label="Footprint volume units" value={units} onChange={e=>setUnits(e.target.value as typeof units)}><option value="base">Base size</option><option value="quote">Quote notional</option></select></label><label>Buy<input type="color" aria-label="Footprint buy color" value={buyColor} onChange={e=>setBuyColor(e.target.value)}/></label><label>Sell<input type="color" aria-label="Footprint sell color" value={sellColor} onChange={e=>setSellColor(e.target.value)}/></label><label>Text<select aria-label="Footprint text size" value={fontSize} onChange={e=>setFontSize(Number(e.target.value))}>{[10,11,12,14].map(n=><option key={n} value={n}>{n}px</option>)}</select></label><button aria-pressed={showPoc} onClick={()=>setShowPoc(v=>!v)}>POC {showPoc?'on':'off'}</button><button onClick={()=>{auto.current=null;setReset(Date.now());}} disabled={!available} aria-label="Reset footprint capture"><RotateCcw size={13}/>Reset capture</button><button onClick={exportCsv} disabled={!result.bars.length} aria-label="Export footprint CSV">CSV</button></div>}
    <div className="fp-statbar"><span>Captured volume<b>{compactVolume(result.total)}</b></span><span>Net delta<b className={result.delta>=0?'cs-positive':'cs-negative'}>{result.delta>0?'+':''}{compactVolume(result.delta)}</b></span><span>Fills<b>{result.trades.toLocaleString()}</b></span><span>Row size<b>{price(result.step)}</b></span><small>{units==='base'?'Base units':'Quote notional'} · UTC</small></div>
    <div className="fp-body"><div className="fp-canvas-wrap"><div ref={host} className="fp-canvas" data-testid="footprint-canvas"/>{!result.bars.length&&<div className="fp-empty"><Layers3 size={30}/><h3>{available?'Waiting for captured trades':replay?'Footprint is paused during replay':'Choose a Hyperliquid market'}</h3><p>{available?'Recent fills and new executions build each footprint. Historical OHLC candles cannot supply bid/ask volume.':replay?'No historical trade recording is available for this replay time. Return to live mode to capture executions.':'Yahoo candles contain total volume, not aggressor trades. Select Hyperliquid in the symbol picker.'}</p></div>}</div>
    <aside className="fp-ladder" aria-label="Selected footprint levels"><div className="fp-ladder-title"><strong>{focused?clock(focused.time):'No bar selected'}</strong><small>{interval/60}m · captured</small></div><div className="fp-selected-stats"><span>Delta <b>{focused?compactVolume(focused.delta):'—'}</b></span><span>POC <b>{focused?price(focused.poc):'—'}</b></span></div><div className="fp-levels"><table><thead><tr><th>Price</th><th>Bid / Sell</th><th>Ask / Buy</th></tr></thead><tbody>{focused?.levels.slice().reverse().map(r=><tr key={r.index} className={focused.poc>=r.low&&focused.poc<r.high?'fp-poc':''} title={`[${price(r.low)}, ${price(r.high)}) · ${r.trades} fills${r.stackedBuy?' · stacked buy':''}${r.stackedSell?' · stacked sell':''}`}><td>{price(r.low)}</td><td className={r.sellImbalance?'fp-sell-imbalance':''}>{compactVolume(r.sell)}{r.stackedSell?' ◆':''}</td><td className={r.buyImbalance?'fp-buy-imbalance':''}>{compactVolume(r.buy)}{r.stackedBuy?' ◆':''}</td></tr>)}</tbody></table></div><p>Sell aggressors hit bids; buy aggressors lift asks. ◆ = 3+ consecutive diagonal imbalances. Gold outline = bar POC.</p></aside></div>
    <div className="fp-footer"><span>Scroll to zoom · drag to pan · hover to inspect. Zoom in for numbers.</span><button aria-label="Zoom footprint out" onClick={()=>zoom(.8)}><Minus size={13}/></button><button aria-label="Zoom footprint in" onClick={()=>zoom(1.25)}><Plus size={13}/></button><button onClick={()=>{setFollow(false);api.current?.timeScale().fitContent();}} aria-label="Fit footprint">Fit</button></div>
    <p className="fp-coverage" role="status">{!validStep?'Enter a positive price step. Last automatic step is displayed. ':''}{result.coarsened?'Rows were widened to keep the price grid within 240 levels. ':''}{feed.gap?'Connection gap: some executions may be missing. ':''}{feed.capped?'20,000-fill retention cap reached. ':''}{result.from?`Coverage ${clock(result.from/1000)}–${clock((result.to||result.from)/1000)} UTC · `:''}Recent seed + received trades only; partial candles, not a complete session. {note}</p>
  </section>;
}
