'use client';
import { useState } from 'react';
import { Settings2, ArrowUpRight, Copy, ChevronsUp, Eye, EyeOff, LockKeyhole, Plus, Trash2, UnlockKeyhole, Code2 } from 'lucide-react';
import { Bar, Dataset, Drawing, Instrument, Interval, INTERVALS, keyOf, Study, StudyResult, WATCHLIST } from '../../../lib/chart-studio/types';
interface Props { tab: string; onTab: (s: string) => void; watchlist: Instrument[]; instrument: Instrument; onInstrument: (i: Instrument) => void; onSearch: () => void; onWatchlist: (v: Instrument[]) => void; studies: Study[]; results: Record<string, StudyResult>; onStudy: (s: Study) => void; onRemove: (id: string) => void; onEdit: (id: string) => void; onSettings: (id: string) => void; drawings: Drawing[]; onDrawings: (d: Drawing[]) => void; data: Dataset | null; bars: Bar[]; compare: string; compareInterval: Interval; onCompare: (v: string, interval: Interval) => void; context: string }
export default function Inspector(p: Props) {
  const [tab, setTab] = [p.tab, p.onTab];
  const last = p.bars.at(-1); const high = p.bars.length ? Math.max(...p.bars.map(b => b.high)) : null; const low = p.bars.length ? Math.min(...p.bars.map(b => b.low)) : null;
  const fmt = (v?: number | null) => v == null ? '—' : v.toLocaleString('en-US', { maximumFractionDigits: 4 });
  return <aside className="cs-inspector"><div className="cs-inspector-tabs">{['Markets', 'Studies', 'Objects', 'Data'].map(t => <button className={t === tab ? 'active' : ''} key={t} onClick={() => setTab(t)}>{t}</button>)}</div>
    <div className="cs-inspector-content">
      {tab === 'Markets' && <><div className="cs-section-heading"><span>WATCHLIST</span><button onClick={p.onSearch} aria-label="Add symbol to watchlist"><Plus size={15} /></button></div><div className="cs-watchlist">{p.watchlist.map(i => <div className={keyOf(i) === keyOf(p.instrument) ? 'active' : ''} key={keyOf(i)}><button onClick={() => p.onInstrument(i)}><span className={`cs-asset-avatar ${i.provider}`}>{i.symbol.slice(0, 1)}</span><span><strong>{i.symbol}</strong><small>{i.provider === 'hyperliquid' ? 'PERPETUAL' : 'YAHOO FINANCE'}</small></span><span className="cs-watch-price">{keyOf(i) === keyOf(p.instrument) ? fmt(last?.close) : <ArrowUpRight size={14} />}</span></button><button aria-label={`Remove ${i.symbol} from watchlist`} className="cs-watch-remove" onClick={() => p.onWatchlist(p.watchlist.filter(v => keyOf(v) !== keyOf(i)))}><Trash2 size={12} /></button></div>)}</div><div className="cs-instrument-card"><span className="cs-eyebrow">ON YOUR CHART</span><h2>{p.instrument.symbol}</h2><p>{p.instrument.name}</p><strong className="cs-big-price">{fmt(last?.close)} <small>{p.data?.currency}</small></strong><dl><div><dt>Visible dataset high</dt><dd>{fmt(high)}</dd></div><div><dt>Visible dataset low</dt><dd>{fmt(low)}</dd></div><div><dt>Candles loaded</dt><dd>{p.bars.length.toLocaleString()}</dd></div></dl><p className="cs-muted">{p.data?.note || 'Waiting for market data'}</p></div></>}
      {tab === 'Studies' && <><div className="cs-section-heading"><span>PYTHON INDICATORS</span><span>{p.studies.length} studies</span></div>{!p.studies.length && <p className="cs-empty">Add a Python template in the editor below.</p>}{p.studies.map(s => { const result = p.results[s.id]; const stale = result && (result.code !== s.code || result.context !== p.context || JSON.stringify(result.params) !== JSON.stringify(s.params)); return <div className="cs-study-card" key={s.id}><div className="cs-study-heading"><button onClick={() => p.onEdit(s.id)}><Code2 size={14} />{s.name}</button><button title="Indicator settings" aria-label={`Settings ${s.name}`} onClick={() => p.onSettings(s.id)}><Settings2 size={14} /></button><button aria-label={`${s.enabled ? 'Hide' : 'Show'} ${s.name}`} onClick={() => p.onStudy({ ...s, enabled: !s.enabled })}>{s.enabled ? <Eye size={14} /> : <EyeOff size={14} />}</button><button aria-label={`Remove ${s.name}`} onClick={() => p.onRemove(s.id)}><Trash2 size={14} /></button></div><input aria-label={`Indicator name ${s.name}`} value={s.name} maxLength={60} onChange={e => p.onStudy({ ...s, name: e.target.value })} /><div className="cs-study-status">{stale ? 'Edited · Run to update chart' : result ? `${result.plots.length} outputs · ${(result.duration / 1000).toFixed(2)}s` : 'Ready · Run to plot'}</div>{result?.inputs.map(param => <label key={param.name} className="cs-parameter">{param.name}<input type="number" min={param.min} max={param.max} step={param.step} value={s.params[param.name] ?? param.value} onChange={e => p.onStudy({ ...s, params: { ...s.params, [param.name]: Number(e.target.value) } })} /></label>)}<label className="cs-check"><input type="checkbox" checked={s.auto} onChange={e => p.onStudy({ ...s, auto: e.target.checked })} />Run on candle close</label></div>; })}</>}
      {tab === 'Objects' && <><div className="cs-section-heading"><span>DRAWING OBJECTS</span><span>{p.drawings.length}</span></div><p className="cs-muted cs-panel-intro">Select a drawing on the chart to move it. Drag its handles to reshape.</p>{!p.drawings.length && <div className="cs-empty">Your chart, your notes.<br />Choose a tool on the left to begin.</div>}{p.drawings.map(d => <div className="cs-object" key={d.id}><input type="color" aria-label={`Color ${d.type}`} value={d.color} onChange={e => p.onDrawings(p.drawings.map(v => v.id === d.id ? { ...v, color: e.target.value } : v))} /><input className="cs-object-name" aria-label="Drawing name" value={d.name || d.text || d.type} maxLength={80} onChange={e => p.onDrawings(p.drawings.map(v => v.id === d.id ? { ...v, name: e.target.value } : v))} /><button aria-label="Duplicate drawing" onClick={() => p.onDrawings([...p.drawings, { ...d, id: crypto.randomUUID(), name: `${d.name || d.type} copy`, locked: false, points: d.points.map(q => ({ ...q, price: q.price + Math.max(Math.abs(q.price) * .001, 1e-8) })) }])}><Copy size={13} /></button><button aria-label="Bring drawing to front" onClick={() => p.onDrawings([...p.drawings.filter(v => v.id !== d.id), d])}><ChevronsUp size={13} /></button><button aria-label={`${d.hidden ? 'Show' : 'Hide'} drawing`} onClick={() => p.onDrawings(p.drawings.map(v => v.id === d.id ? { ...v, hidden: !v.hidden } : v))}>{d.hidden ? <EyeOff size={13} /> : <Eye size={13} />}</button><button aria-label={`${d.locked ? 'Unlock' : 'Lock'} drawing`} onClick={() => p.onDrawings(p.drawings.map(v => v.id === d.id ? { ...v, locked: !v.locked } : v))}>{d.locked ? <LockKeyhole size={13} /> : <UnlockKeyhole size={13} />}</button><button disabled={d.locked} aria-label="Delete drawing" onClick={() => p.onDrawings(p.drawings.filter(v => v.id !== d.id))}><Trash2 size={13} /></button></div>)}</>}
      {tab === 'Data' && <><div className="cs-section-heading"><span>DATA PROVENANCE</span></div><dl className="cs-data-details"><div><dt>Provider</dt><dd>{p.instrument.provider}</dd></div><div><dt>Symbol</dt><dd>{p.instrument.symbol}</dd></div><div><dt>Session timezone</dt><dd>{p.data?.timezone || '—'}</dd></div><div><dt>Last received</dt><dd>{p.data ? new Date(p.data.asOf).toLocaleTimeString() : '—'}</dd></div><div><dt>History starts</dt><dd>{p.bars[0] ? new Date(p.bars[0].time * 1000).toLocaleDateString() : '—'}</dd></div></dl><p className="cs-muted cs-panel-intro">{p.data?.note}</p><div className="cs-section-heading"><span>MARKET CONTEXT</span></div>{p.data?.market ? <dl className="cs-data-details"><div><dt>Mark price</dt><dd>{fmt(p.data.market.markPrice)}</dd></div><div><dt>Oracle price</dt><dd>{fmt(p.data.market.oraclePrice)}</dd></div><div><dt>Open interest (base)</dt><dd>{fmt(p.data.market.openInterest)}</dd></div><div><dt>Funding rate</dt><dd>{(p.data.market.funding * 100).toFixed(5)}%</dd></div><div><dt>24h notional volume</dt><dd>{fmt(p.data.market.volume24h)}</dd></div></dl> : <p className="cs-muted cs-panel-intro">{p.instrument.provider === 'hyperliquid' ? 'Waiting for live asset context…' : 'Funding and perpetual OI are not available from Yahoo OHLCV.'}</p>}<p className="cs-muted cs-panel-intro">ctx.market is a current snapshot, not historical data. It is unavailable to scripts during replay.</p><div className="cs-section-heading"><span>PYTHON DATA INPUTS</span></div><p className="cs-muted cs-panel-intro">Add a second symbol or timeframe. Read it with <code>ctx.data.ohlcv("compare")</code>.</p><label className="cs-field-label">Compare dataset<select value={p.compare} onChange={e => p.onCompare(e.target.value, p.compareInterval)}><option value="">None</option>{Array.from(new Map([...WATCHLIST, ...p.watchlist].map(i => [keyOf(i), i])).values()).map(i => <option value={keyOf(i)} key={keyOf(i)}>{i.symbol} · {i.provider}</option>)}</select></label><label className="cs-field-label">Compare timeframe<select value={p.compareInterval} onChange={e => p.onCompare(p.compare, e.target.value as Interval)}>{INTERVALS.map(i => <option key={i}>{i}</option>)}</select></label><p className="cs-muted cs-panel-intro">Auxiliary bars become available at their close time. Missing history stays missing. Yahoo OHLCV does not contain aggressor trade delta.</p></>}
    </div><div className="cs-inspector-footer"><span className="cs-status-dot" />LOCAL WORKSPACE<span>v1.0</span></div>
  </aside>;
}
