'use client';
import { useEffect, useMemo, useState } from 'react';
import { Download, RotateCcw } from 'lucide-react';
import { Bar, Instrument } from '../../../lib/chart-studio/types';
import { depthStats, flowStats, FlowTrade, VolumeProfile, volumeProfile } from '../../../lib/chart-studio/orderflow';
import { useOrderFlow } from '../../../lib/chart-studio/useOrderFlow';

interface Props { instrument: Instrument; bars: Bar[]; intervalSeconds: number; flow: boolean; profile: boolean; replay: boolean; range: { from: number; to: number } | null; onProfile: (profile: VolumeProfile | null) => void }
const fmt = (n?: number | null, digits = 3) => n == null ? '—' : n.toLocaleString('en-US', { maximumFractionDigits: digits });
const clock = (n: number) => new Date(n).toLocaleTimeString('en-GB', { hour12: false });
const NO_TRADES: FlowTrade[] = [];
export default function MarketMicrostructure(p: Props) {
  const [source, setSource] = useState<'candles' | 'trades'>('candles'); const [rangeMode, setRangeMode] = useState('visible');
  const [rows, setRows] = useState(48); const [va, setVA] = useState(70); const [windowMinutes, setWindowMinutes] = useState(5);
  const [levels, setLevels] = useState(10); const [minimum, setMinimum] = useState(0); const [reset, setReset] = useState(0);
  const available = p.instrument.provider === 'hyperliquid' && !p.replay;
  const feed = useOrderFlow(p.instrument.symbol, available && (p.flow || p.profile && source === 'trades'), reset);
  const cutoff = feed.now - windowMinutes * 60000;
  const trades = useMemo(() => feed.trades.filter(t => t.time >= cutoff), [feed.trades, cutoff]);
  const stats = useMemo(() => flowStats(trades, Math.max(1000, windowMinutes * 500)), [trades, windowMinutes]);
  const depth = useMemo(() => depthStats(feed.book, levels), [feed.book, levels]);
  const profileTrades = source === 'trades' ? trades : NO_TRADES;
  const profile = useMemo(() => {
    if (!p.profile || source === 'trades' && !available) return null;
    const inRange = (time: number, trade = false) => rangeMode !== 'visible' || !p.range || time >= p.range.from && (trade ? time < p.range.to + p.intervalSeconds : time <= p.range.to);
    return volumeProfile(source, profileTrades.filter(t => inRange(t.time / 1000, true)), p.bars.filter(b => inRange(b.time)), rows, va / 100);
  }, [p.profile, p.bars, p.range, p.intervalSeconds, source, available, profileTrades, rangeMode, rows, va]);
  useEffect(() => { p.onProfile(profile); }, [profile, p.onProfile]);
  useEffect(() => () => p.onProfile(null), [p.onProfile]);
  const tape = trades.filter(t => t.price * t.size >= minimum).slice(-40).reverse();
  const cvd = stats.cvd; const values = [0, ...cvd.map(t => t.value)]; const min = Math.min(...values), max = Math.max(...values);
  const y = (value: number) => 68 - (value - min) / (max - min || 1) * 56;
  const path = cvd.length ? `M8,${y(0)} ` + cvd.map((c, i) => `L${8 + (i + 1) / cvd.length * 284},${y(c.value)}`).join(' ') : '';
  const bookStale = !feed.book || feed.now - feed.book.time > 15000;
  const depthMax = Math.max(1e-12, ...depth.bids.map(b => b.size), ...depth.asks.map(b => b.size));
  function download() {
    const text = ['time_utc,side,price,size_base,notional', ...trades.map(t => `${new Date(t.time).toISOString()},${t.side},${t.price},${t.size},${t.price * t.size}`)].join('\n');
    const url = URL.createObjectURL(new Blob([text], { type: 'text/csv' })); const a = document.createElement('a'); a.href = url; a.download = `${p.instrument.symbol.replace(/[^\w-]/g, '_')}-trades.csv`; a.click(); URL.revokeObjectURL(url);
  }
  return <section className="cs-microstructure" aria-label="Order flow and volume profile">
    {p.profile && <div className="cs-profile-controls"><strong>VOLUME PROFILE</strong><label>Source<select aria-label="Volume profile source" value={source} onChange={e => setSource(e.target.value as typeof source)}><option value="candles">Candles · estimated</option><option value="trades" disabled={!available}>Trades · captured</option></select></label><label>Range<select aria-label="Volume profile range" value={rangeMode} onChange={e => setRangeMode(e.target.value)}><option value="visible">Visible chart</option><option value="loaded">{source === 'trades' ? 'Captured window' : 'Loaded candles'}</option></select></label><label>Rows<select aria-label="Volume profile rows" value={rows} onChange={e => setRows(Number(e.target.value))}>{[24, 48, 96].map(n => <option key={n}>{n}</option>)}</select></label><label>Value area<select aria-label="Value area percent" value={va} onChange={e => setVA(Number(e.target.value))}>{[68, 70, 80, 90].map(n => <option value={n} key={n}>{n}%</option>)}</select></label><div className="cs-profile-levels"><span>POC <b>{fmt(profile?.poc)}</b></span><span>VAH <b>{fmt(profile?.vah)}</b></span><span>VAL <b>{fmt(profile?.val)}</b></span></div><p className="cs-profile-note">{profile ? `${source === 'trades' ? 'Executed volume · green buy / red sell' : 'Estimated volume · uniform high–low allocation; no buy/sell inference'} · ${fmt(profile.total)} base · actual VA ${fmt(profile.actualValueArea * 100, 1)}%` : source === 'trades' ? available ? 'No captured trades in this range. Use Captured window or return to the latest candles.' : 'Live trade profile is unavailable for Yahoo or historical replay. Choose Candles.' : 'No candle volume in this range.'}</p></div>}
    {(p.flow || p.profile && source === 'trades') && <div className="cs-flow-header"><div><strong>ORDER FLOW</strong><span>{p.instrument.symbol}</span><span className={available && !bookStale ? 'cs-positive' : 'cs-muted'} role="status">{!available ? 'Unavailable' : bookStale ? `${feed.status} · waiting / stale book` : feed.status}</span></div><div><label>Window<select aria-label="Order flow window" value={windowMinutes} onChange={e => setWindowMinutes(Number(e.target.value))}>{[1, 5, 15, 60].map(n => <option value={n} key={n}>{n}m</option>)}</select></label><button disabled={!available} onClick={() => setReset(Date.now())} title="Clear captured trades and restart delta" aria-label="Reset order flow"><RotateCcw size={13} />Reset</button><button disabled={!trades.length} onClick={download} aria-label="Export captured trades"><Download size={13} />CSV</button></div></div>}
    {p.flow && (!available ? <p className="cs-flow-unavailable">{p.replay ? 'Order flow is paused during replay. Historical trades and book snapshots have not been recorded.' : 'Select a Hyperliquid market for executed trades and order-book depth. Yahoo provides candle volume only.'}</p> : <div className="cs-flow-grid">
      <div className="cs-flow-summary"><div className="cs-flow-title">AGGRESSOR FLOW <span>base units</span></div><div className="cs-flow-metrics"><div><small>Buy volume</small><b className="cs-positive">{fmt(stats.buy)}</b></div><div><small>Sell volume</small><b className="cs-negative">{fmt(stats.sell)}</b></div><div><small>Window delta</small><b className={stats.delta >= 0 ? 'cs-positive' : 'cs-negative'}>{stats.delta >= 0 ? '+' : ''}{fmt(stats.delta)}</b></div></div><div className="cs-aggression-bar"><i style={{ width: `${(stats.buyRatio ?? .5) * 100}%` }} /></div><div className="cs-flow-title">CUMULATIVE VOLUME DELTA <span>{stats.buyRatio == null ? 'No trades' : `${fmt(stats.buyRatio * 100, 1)}% buy`}</span></div><svg className="cs-cvd-chart" viewBox="0 0 300 80" role="img" aria-label="Cumulative volume delta for captured window"><line x1="8" x2="292" y1={y(0)} y2={y(0)} stroke="var(--cs-border)" strokeDasharray="3 4" /><path d={path} fill="none" stroke={stats.delta >= 0 ? 'var(--cs-accent)' : 'var(--cs-red)'} strokeWidth="1.5" /></svg><p className="cs-flow-footnote">{trades.length ? `${trades.length.toLocaleString()} captured fills · ${clock(trades[0].time)}–${clock(trades[trades.length - 1].time)}` : 'Waiting for executed trades…'}<br />CVD starts at zero for this retained window. Recent-trades seed; not a full session.</p></div>
      <div className="cs-flow-book"><div className="cs-flow-title">ORDER BOOK <select aria-label="Order book levels" value={levels} onChange={e => setLevels(Number(e.target.value))}>{[5, 10, 20].map(n => <option value={n} key={n}>{n} levels</option>)}</select></div><div className="cs-book-summary"><span>Spread <b>{fmt(depth.spread, 6)}</b></span><span>{fmt(depth.spreadBps, 2)} bps</span><span>Imbalance <b>{bookStale || depth.imbalance == null ? '—' : `${fmt(depth.imbalance * 100, 1)}%`}</b></span></div><div className={`cs-depth-table ${bookStale ? 'cs-book-stale' : ''}`}><div className="cs-depth-row cs-depth-labels"><span>Bid size</span><span>Bid</span><span>Ask</span><span>Ask size</span></div>{Array.from({ length: Math.max(depth.bids.length, depth.asks.length) }, (_, i) => { const bid = depth.bids[i], ask = depth.asks[i]; return <div className="cs-depth-row" key={i}><span className="cs-positive" style={{ background: `linear-gradient(to left, color-mix(in srgb, var(--cs-accent) 20%, transparent) ${100 * (bid?.size || 0) / depthMax}%, transparent 0)` }}><b>{fmt(bid?.size)}</b></span><span className="cs-positive">{fmt(bid?.price, 5)}</span><span className="cs-negative">{fmt(ask?.price, 5)}</span><span className="cs-negative" style={{ background: `linear-gradient(to right, color-mix(in srgb, var(--cs-red) 20%, transparent) ${100 * (ask?.size || 0) / depthMax}%, transparent 0)` }}><b>{fmt(ask?.size)}</b></span></div>; })}</div><p className="cs-flow-footnote">Top {levels} levels · resting size can cancel. {feed.book ? `Book ${clock(feed.book.time)}${bookStale ? ' · STALE' : ''}` : 'Waiting for depth…'}</p></div>
      <div className="cs-flow-tape"><div className="cs-flow-title">TIME & SALES <label>Min notional<input aria-label="Minimum trade notional" type="number" min="0" value={minimum} onChange={e => setMinimum(Math.max(0, Number(e.target.value) || 0))} /></label></div><div className="cs-tape-table"><div className="cs-tape-row cs-depth-labels"><span>Time</span><span>Side</span><span>Price</span><span>Size</span></div>{tape.map(t => <div className={`cs-tape-row ${t.side === 'buy' ? 'cs-positive' : 'cs-negative'}`} key={t.id}><time>{clock(t.time)}</time><span>{t.side === 'buy' ? 'BUY' : 'SELL'}</span><span>{fmt(t.price, 5)}</span><span>{fmt(t.size, 5)}</span></div>)}</div><p className="cs-flow-footnote">Latest 40 matching fills. Tape filter does not change delta or profile.</p></div>
    </div>)}
    {available && (feed.gap || feed.capped) && <p className="cs-flow-warning" role="status">{feed.gap ? 'Connection gap detected: CVD and trade profile cover received fills only. ' : ''}{feed.capped ? '20,000-trade retention limit reached; older fills are excluded.' : ''}</p>}
  </section>;
}
