'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Download, RefreshCw } from 'lucide-react';
import { ConstituentResearch, ExposureSummary, numberLabel as n, researchCsv, researchFetch } from '../../lib/greeksResearch';
import { ResearchMetric, ResearchState, useResearch } from './ResearchPanelShell';

const ETFS = ['SPY', 'QQQ', 'IWM', 'DIA', 'XLK', 'SMH', 'XLF', 'XLE'];
function ExposureCard({ symbol, value, error }: { symbol: string; value?: ExposureSummary; error?: string }) {
  const amount = value?.net_gex;
  return <div className="min-w-0 flex-1 rounded-lg border border-zinc-700 bg-zinc-950 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-lg text-zinc-100">{symbol}</strong><span className={`text-xs ${amount == null ? 'text-zinc-400' : amount < 0 ? 'text-rose-300' : 'text-emerald-300'}`}>{amount == null ? 'GEX unavailable' : amount < 0 ? 'Model negative' : amount > 0 ? 'Model positive' : 'Model neutral'}</span></div><p className="mt-3 text-2xl text-zinc-100">{amount == null ? '—' : `${amount >= 0 ? '+' : '−'}$${n(Math.abs(amount) / 1e6)}M`}</p><p className="mt-1 text-[10px] text-zinc-400">USD delta exposure per 1% move in its own underlying</p>{value && <div className="mt-3 space-y-1 text-xs text-zinc-400"><p>Net / gross: {value.balance == null ? '—' : n(value.balance * 100) + '%'}</p><p>Gamma flip: {value.gamma_flip == null ? '—' : '$' + n(value.gamma_flip)}</p><p>Source: {value.source} · {value.stale ? 'stale cache' : 'cached snapshot'}</p><p className="break-words">{value.timestamp || 'Timestamp unavailable'} (server time)</p><p>{value.note}</p></div>}{error && <p role="alert" className="mt-3 text-xs text-amber-300">{error}</p>}</div>;
}
export default function EtfConstituentPanel({ initialTicker }: { initialTicker: string }) {
  const [etf, setEtf] = useState(ETFS.includes(initialTicker) ? initialTicker : 'SPY');
  const [window, setWindow] = useState(60); const [query, setQuery] = useState('');
  const [selected, setSelected] = useState(''); const [loadingPair, setLoadingPair] = useState(false);
  const [exposures, setExposures] = useState<Record<string, ExposureSummary>>({}); const [exposureErrors, setExposureErrors] = useState<Record<string, string>>({});
  const pending = useRef<AbortController>();
  const { data, busy, error, retry } = useResearch<ConstituentResearch>(`etf-constituents?etf=${etf}&window=${window}`);
  useEffect(() => { pending.current?.abort(); setSelected(''); setExposures({}); setExposureErrors({}); setLoadingPair(false); return () => pending.current?.abort(); }, [etf]);
  async function compare(symbol: string) {
    pending.current?.abort(); const request = new AbortController(); pending.current = request;
    setSelected(symbol); setLoadingPair(true); setExposureErrors({});
    await Promise.all([etf, symbol].map(async ticker => {
      try { const value = await researchFetch<ExposureSummary>(`constituent-exposure?ticker=${encodeURIComponent(ticker)}`, request.signal); if (!request.signal.aborted) setExposures(old => ({ ...old, [ticker]: value })); }
      catch (e) { if (!request.signal.aborted) setExposureErrors(old => ({ ...old, [ticker]: e instanceof Error ? e.message : 'Exposure unavailable' })); }
    }));
    if (!request.signal.aborted) setLoadingPair(false);
  }
  const rows = data?.rows.filter(row => (row.symbol + ' ' + row.name).toLowerCase().includes(query.toLowerCase())) || [];
  const child = data?.rows.find(row => row.symbol === selected);
  const parentGamma = exposures[etf]?.net_gex, childGamma = exposures[selected]?.net_gex;
  return <section aria-label="ETF constituent research" className="space-y-4">
    <div className="rounded-xl border border-zinc-800 bg-zinc-900/30 p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] tracking-widest text-cyan-400">ETF → TOP HOLDINGS → INDEPENDENT OPTIONS EXPOSURE</p><h4 className="mt-1 text-lg font-semibold text-zinc-100">ETF–constituent map</h4><p className="mt-2 max-w-3xl text-xs leading-relaxed text-zinc-400">Lihat keterkaitan return dan bandingkan GEX dari chain masing-masing. Gamma ETF tidak diwariskan ke saham penyusunnya.</p></div><button onClick={retry} disabled={busy} className="flex items-center gap-2 rounded border border-zinc-700 px-3 py-2 text-xs text-zinc-300 disabled:opacity-50"><RefreshCw size={13} />Reload holdings</button></div>
      <div className="mt-5 flex flex-wrap items-center gap-3 text-xs"><label className="flex items-center gap-2 text-zinc-400">ETF<select aria-label="ETF selection" value={etf} onChange={e => setEtf(e.target.value)} className="rounded border border-zinc-700 bg-zinc-950 p-2 text-zinc-200">{ETFS.map(t => <option key={t}>{t}</option>)}</select></label><label className="flex items-center gap-2 text-zinc-400">Returns window<select aria-label="Constituent returns window" value={window} onChange={e => setWindow(Number(e.target.value))} className="rounded border border-zinc-700 bg-zinc-950 p-2 text-zinc-200"><option value={20}>20 observations</option><option value={60}>60 observations</option><option value={120}>120 observations</option></select></label><input className="min-w-0 rounded border border-zinc-700 bg-zinc-950 px-3 py-2 text-zinc-200" aria-label="Filter constituents" placeholder="Search stock or company" value={query} onChange={e => setQuery(e.target.value)} /></div>
    </div>
    <ResearchState busy={busy} error={error} retry={retry} />
    {data && data.etf === etf && <>
      <p className="text-xs leading-relaxed text-zinc-400">Holdings effective date: {data.holdings_asof || "not supplied by provider"} · Retrieved {data.retrieved_at.slice(0, 10)}. Weights below cover only the returned holdings.</p>
      <div className="grid grid-cols-2 overflow-hidden rounded-xl border border-zinc-800 bg-zinc-900/30 lg:grid-cols-4"><ResearchMetric label="ETF" value={etf} detail="Local selection for this panel" /><ResearchMetric label="Holdings returned" value={String(data.rows.length)} detail="Provider top holdings; not full portfolio" /><ResearchMetric label="Weight coverage" value={`${n(data.coverage * 100)}%`} detail="Sum of returned weights, not renormalized" /><ResearchMetric label="Prices through" value={data.price_asof} detail="Adjusted daily closes; current date excluded" /></div>
      <div className="overflow-hidden rounded-xl border border-zinc-800"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-800 bg-zinc-900/30 p-4 text-xs"><span className="text-zinc-400">Click Compare GEX to load two independent option chains.</span><button className="flex items-center gap-2 text-cyan-300" onClick={() => researchCsv(`${etf}-constituents.csv`, data.rows.map(row => ({ etf, ...row, holdings_asof: data.holdings_asof, retrieved_at: data.retrieved_at })))}><Download size={13} />Export CSV</button></div><div className="overflow-x-auto"><table className="w-full min-w-[750px] text-left text-xs"><thead className="bg-zinc-950 text-[10px] uppercase tracking-wider text-zinc-400"><tr>{['Constituent', 'ETF weight', 'Beta vs ETF', 'Correlation', 'Relative 20 obs.', 'Samples / date', 'Options'].map(title => <th className="px-4 py-3 font-normal" key={title}>{title}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.symbol} className={`border-t border-zinc-800 ${selected === row.symbol ? 'bg-cyan-950/20' : 'bg-zinc-900/10 hover:bg-zinc-900/50'}`}><td className="px-4 py-3"><strong className="text-zinc-100">{row.symbol}</strong><p className="mt-1 max-w-40 truncate text-[10px] text-zinc-400" title={row.name}>{row.name}</p></td><td className="px-4 py-3 text-zinc-200">{n(row.weight * 100)}%<div className="mt-1 h-1 w-20 bg-zinc-800"><div className="h-1 bg-cyan-500" style={{ width: `${Math.min(100, row.weight * 100)}%` }} /></div></td><td className="px-4 py-3 text-zinc-200">{n(row.beta)}</td><td className="px-4 py-3 text-zinc-200">{n(row.correlation)}</td><td className="px-4 py-3 text-zinc-200">{row.relative_return_20 == null ? '—' : `${row.relative_return_20 >= 0 ? '+' : ''}${n(row.relative_return_20)}%`}</td><td className="px-4 py-3 text-zinc-400">{row.samples} / {row.asof || '—'}{row.error && <p className="mt-1 max-w-48 text-[10px] text-amber-300">{row.error}</p>}</td><td className="px-4 py-3"><button aria-label={`Compare ${etf} and ${row.symbol} GEX`} onClick={() => void compare(row.symbol)} className="rounded border border-zinc-700 px-2 py-2 text-cyan-300">Compare GEX</button></td></tr>)}</tbody></table>{!rows.length && <p role="status" className="p-6 text-sm text-zinc-400">No holdings match this filter.</p>}</div></div>
      {selected && <div className="space-y-3 rounded-xl border border-zinc-800 bg-zinc-900/30 p-4"><div className="flex flex-wrap justify-between gap-2"><h4 className="text-sm text-zinc-200">{etf} ↔ {selected} · exposure comparison</h4><button onClick={() => void compare(selected)} disabled={loadingPair} className="text-xs text-cyan-300 disabled:opacity-50">Refresh pair</button></div>{loadingPair && <p role="status" className="text-xs text-cyan-300">Loading cached/provider option chains…</p>}<div className="flex flex-col items-stretch gap-3 lg:flex-row"><ExposureCard symbol={etf} value={exposures[etf]} error={exposureErrors[etf]} /><div className="flex items-center justify-center text-zinc-500"><ArrowRight size={20} /></div><ExposureCard symbol={selected} value={exposures[selected]} error={exposureErrors[selected]} /></div><p className="text-xs leading-relaxed text-zinc-400">{parentGamma != null && childGamma != null ? Math.sign(parentGamma) === Math.sign(childGamma) ? 'The model signs agree in these snapshots. This does not establish causal transmission or predict price direction.' : 'The model signs differ: ETF positioning does not determine the sign of the constituent’s own options exposure.' : 'A comparison requires two provider-backed chains. Missing or synthetic values stay unavailable.'} {child ? `Return correlation ${n(child.correlation)}; beta ${n(child.beta)} over ${child.samples} paired observations.` : ''}</p></div>}
      <details className="rounded-xl border border-zinc-800 p-4 text-xs leading-relaxed text-zinc-400"><summary className="cursor-pointer text-zinc-200">Sources, assumptions & interpretation</summary><div className="mt-4 space-y-3"><p>{data.note}</p><p>Source: {data.source}. Holdings effective date: {data.holdings_asof || 'not supplied'}. Retrieved: {data.retrieved_at}. Cache up to 15 minutes.</p><p>Beta = covariance(stock return, ETF return) / variance(ETF return). Adjusted daily returns are paired on identical start and end dates, with no forward fill. At least 20 pairs are required. Relative return = stock growth / ETF growth − 1 over 20 common closing intervals.</p><p>GEX model uses call + / put −, aggregate engine expiry buckets through approximately 30DTE. Each value is USD delta exposure for a 1% move in its own underlying. These are separate shocks; multiplying ETF GEX by portfolio weight does not produce the stock’s own GEX. Dealer positions, hedge execution and cross-product offsets are unobserved.</p><p>Negative gamma is not a directional sell signal. A Bayesian analysis can use these observations as evidence, but this panel does not invent posterior probabilities from model signs.</p></div></details>
    </>}
  </section>;
}
