const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs'),path=require('path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome',args:['--force-device-scale-factor=2']});try{
 const page=await browser.newPage({viewport:{width:1500,height:1000},deviceScaleFactor:2});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const end=Math.floor(Date.now()/3600000)*3600;const bars=Array.from({length:300},(_,i)=>{const open=100+i*.02+Math.sin(i/12)*2,close=open+Math.sin(i)*.4;return {time:end-(299-i)*3600,open,close,high:Math.max(open,close)+.3,low:Math.min(open,close)-.3,volume:100+i%60}});
 await page.route('**/api/chart-studio/bars?**',r=>r.fulfill({json:{bars,currency:'USD',timezone:'UTC',asOf:Date.now(),note:'Deterministic appearance fixture'}}));await page.route('**/api/chart-studio/stream?**',r=>r.abort());
 await page.goto('http://127.0.0.1:3000/terminal',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!document.querySelector('.cs-chart-empty'));
 assert.equal(await page.locator('.cs-python').count(),0,'chart starts with editor collapsed');
 const box=await page.locator('.cs-drawing-layer').boundingBox();const at=(x,y)=>({x:box.x+x,y:box.y+y});
 const click=async(x,y)=>{const q=at(x,y);await page.mouse.click(q.x,q.y)};
 const drag=async(x,y,dx,dy)=>{const q=at(x,y);await page.mouse.move(q.x,q.y);await page.mouse.down();await page.mouse.move(q.x+dx,q.y+dy,{steps:12});await page.mouse.up()};
 await page.getByRole('button',{name:'Trendline',exact:true}).click();await click(220,180);await page.mouse.move(box.x+450,box.y+250);await click(450,250);
 await page.waitForSelector('.cs-drawing-properties');assert.equal(await page.locator('[data-drawing-id]').count(),1);
 const id=await page.locator('[data-drawing-id]').getAttribute('data-drawing-id');const drawing=page.locator('[data-drawing-id="'+id+'"]');
 const coords=()=>drawing.locator('g').first().locator('line').evaluate(e=>['x1','y1','x2','y2'].map(k=>Number(e.getAttribute(k))));
 let before=await coords();await page.getByRole('button',{name:'Deselect drawing'}).click();await click(335,220);await page.waitForSelector('.cs-drawing-properties');
 await page.getByLabel('Drawing line width',{exact:true}).selectOption('3');await page.getByLabel('Drawing line style',{exact:true}).selectOption('dashed');assert.equal(await drawing.getAttribute('stroke-width'),'3');
 await page.getByRole('button',{name:'Chart settings',exact:true}).click();await page.getByLabel('Bullish body',{exact:true}).fill('#33ccff');await page.getByLabel('Bearish body',{exact:true}).fill('#ff9900');await page.getByRole('button',{name:'Canvas',exact:true}).click();await page.getByLabel('Chart background',{exact:true}).fill('#0b1020');await page.getByLabel('Grid lines',{exact:true}).selectOption('none');
 for(let i=0;i<12;i++){await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>Boolean(document.activeElement.closest('dialog'))),'focus stays in settings')}
 await page.getByRole('button',{name:'Done',exact:true}).click();let after=await coords();before.forEach((n,i)=>assert.ok(Math.abs(n-after[i])<1,'appearance preserves viewport'));
 assert.ok(await page.evaluate(()=>Array.from(document.querySelectorAll('.cs-chart-canvas canvas')).filter(c=>c.width>0).every(c=>c.width>=c.getBoundingClientRect().width*1.95)),'HiDPI backing resolution');
 await drag(335,215,60,35);after=await coords();assert.ok(Math.abs(after[0]-before[0]-60)<2);assert.ok(Math.abs(after[1]-before[1]-35)<2);
 await page.getByRole('button',{name:'Lock selected drawing'}).click();const locked=await coords();await drag(395,250,40,30);assert.deepEqual(await coords(),locked);await page.getByRole('button',{name:'Unlock selected drawing'}).click();
 await page.getByRole('button',{name:'Duplicate selected drawing'}).click();assert.equal(await page.locator('[data-drawing-id]').count(),2);await page.keyboard.press('Control+z');assert.equal(await page.locator('[data-drawing-id]').count(),1);await page.keyboard.press('Control+Shift+z');assert.equal(await page.locator('[data-drawing-id]').count(),2);
 await page.getByRole('button',{name:'Rectangle / zone',exact:true}).click();await drag(520,300,140,90);assert.equal(await page.locator('[data-selected="true"] [data-handle]').count(),4);const corner=await page.locator('[data-selected="true"] [data-handle="2"]').boundingBox();await page.mouse.move(corner.x+5,corner.y+5);await page.mouse.down();await page.mouse.move(corner.x-35,corner.y+35,{steps:8});await page.mouse.up();
 await page.getByRole('button',{name:'Long position',exact:true}).click();await drag(720,300,120,-100);assert.match(await page.locator('[data-selected="true"] text').textContent(),/R:R 2.00/);const stop=await page.locator('[data-selected="true"] [data-handle="2"]').boundingBox();await page.mouse.move(stop.x+5,stop.y+5);await page.mouse.down();await page.mouse.move(stop.x+5,stop.y+55,{steps:8});await page.mouse.up();assert.doesNotMatch(await page.locator('[data-selected="true"] text').textContent(),/R:R 2.00/);
 await page.getByRole('button',{name:'Text note',exact:true}).click();await click(550,120);await page.getByLabel('Chart note text').fill('Supply zone · watch reaction');await page.getByRole('button',{name:'Save note',exact:true}).click();assert.match(await page.locator('[data-selected="true"] text').textContent(),/Supply zone/);
 await page.getByRole('button',{name:'Trendline',exact:true}).click();await click(300,400);await page.keyboard.press('Escape');assert.equal(await page.locator('[data-drawing-id]').count(),5,'Escape discards unfinished drawing');
 await page.getByRole('button',{name:'Stay in drawing mode'}).click();await page.getByRole('button',{name:'Horizontal line',exact:true}).click();await click(300,450);await click(300,480);assert.equal(await page.locator('[data-drawing-id]').count(),7);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Stay in drawing mode'}).click();
 await page.mouse.move(box.x+500,box.y+350);await page.mouse.wheel(0,-500);await page.waitForTimeout(300);assert.ok(await page.evaluate(()=>Array.from(document.querySelectorAll('.cs-chart-canvas canvas')).every(c=>c.width>=c.getBoundingClientRect().width*1.95)));
 await page.getByRole('button',{name:'Save',exact:true}).click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('vrp.chart-studio.v1')));assert.equal(saved.appearance.background,'#0b1020');assert.equal(saved.appearance.up,'#33ccff');
 const imageDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export chart PNG',exact:true}).click();const png=await imageDownload;assert.ok(png.suggestedFilename().endsWith('.png'));
 const dest=path.resolve(__dirname,'../../.ua/chart-studio');fs.mkdirSync(dest,{recursive:true});await page.screenshot({path:path.join(dest,'appearance-desktop.png'),fullPage:true});
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('[data-drawing-id]');assert.equal(await page.locator('[data-drawing-id]').count(),7);await page.getByRole('button',{name:'Chart settings',exact:true}).click();assert.equal(await page.getByLabel('Bullish body',{exact:true}).inputValue(),'#33ccff');await page.getByRole('button',{name:'Canvas',exact:true}).click();assert.equal(await page.getByLabel('Chart background',{exact:true}).inputValue(),'#0b1020');await page.screenshot({path:path.join(dest,'appearance-settings.png'),fullPage:true});await page.keyboard.press('Escape');
 for(const width of [1024,768,390,320]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'no horizontal overflow at '+width);await page.screenshot({path:path.join(dest,'appearance-'+width+'.png'),fullPage:true})}
 assert.deepEqual(errors,[]);console.log('PASS appearance persistence, focus, viewport retention, 2x canvas/zoom, click-click/drag, hit areas, styles, locks, duplicates, undo/redo, rectangle/position handles, notes, Escape, repeat mode and responsive');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
