const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true,args:['--force-device-scale-factor=2']});try{
 const page=await browser.newPage({viewport:{width:1500,height:1040},deviceScaleFactor:2});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{
  localStorage.setItem('vrp.chart-studio.v1',JSON.stringify({version:1,name:'Footprint test',instrument:{provider:'hyperliquid',symbol:'BTC',name:'Bitcoin'},interval:'1m',studies:[],drawings:{},watchlist:[],light:false}));
  const Native=window.EventSource;window.__sources=[];window.__closed=0;
  window.EventSource=class {constructor(url){if(!String(url).includes('/orderflow?'))return new Native(url);this.url=url;this.onmessage=null;this.onerror=null;window.__sources.push(this);setTimeout(()=>{const end=Math.floor(Date.now()/60000)*60000;const trades=[];let id=0;for(let b=0;b<8;b++)for(let row=0;row<14;row++){const price=90000+(b%4)*15+row*5;for(const side of ['sell','buy'])trades.push({id:String(++id),time:end-(7-b)*60000+row*1000,price,size:side==='buy'?(b%3===0?.04:.4):.08,side})}this.onmessage?.({data:JSON.stringify({type:'flow',trades,status:'Live',book:null})})},50)}close(){window.__closed++;window.__sources=window.__sources.filter(x=>x!==this)}};
 });
 await page.route('**/api/chart-studio/bars?*',r=>r.fulfill({json:{bars:Array.from({length:100},(_,i)=>({time:Math.floor(Date.now()/60000)*60-(99-i)*60,open:90000,close:90010,high:90020,low:89990,volume:10})),currency:'USDC',timezone:'UTC',asOf:Date.now()}}));
 await page.route('**/api/chart-studio/stream?*',r=>r.abort());await page.route('**/api/chart-studio/search?*',r=>r.fulfill({json:[]}));
 await page.goto('http://127.0.0.1:3000/terminal',{waitUntil:'domcontentloaded',timeout:90000});await page.getByRole('button',{name:'Toggle footprint chart'}).click();await page.waitForFunction(()=>document.querySelector('.fp-statbar')?.textContent.includes('224'));
 const canvas=page.locator('.fp-canvas canvas').first();await canvas.waitFor();assert.ok(await canvas.evaluate(c=>c.width/c.clientWidth>=1.9),'native high DPI backing canvas');await page.getByLabel('Footprint price per row').fill('5');await page.waitForFunction(()=>document.querySelectorAll('.fp-levels tbody tr').length===14);
 const out=path.resolve(__dirname,'../../.ua/footprint');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'footprint-desktop.png')});
 await page.getByLabel('Footprint settings').click();await page.getByLabel('Footprint imbalance ratio').selectOption('3');assert.ok(await page.locator('.fp-buy-imbalance').count()>0);await page.getByLabel('Footprint buy color').fill('#ff00aa');await page.getByLabel('Footprint text size').selectOption('14');await page.getByLabel('Footprint view').selectOption('delta');
 const [png]=await Promise.all([page.waitForEvent('download'),page.getByLabel('Export footprint PNG').click()]);assert.equal(png.suggestedFilename(),'footprint.png');await png.saveAs(path.join(out,'footprint-export.png'));
 const [csv]=await Promise.all([page.waitForEvent('download'),page.getByLabel('Export footprint CSV').click()]);const csvPath=path.join(out,'footprint.csv');await csv.saveAs(csvPath);assert.match(fs.readFileSync(csvPath,'utf8'),/bid_sell,ask_buy,delta/);
 await page.getByLabel('Footprint volume units').selectOption('quote');assert.ok((await page.locator('.fp-statbar').innerText()).includes('Quote notional'));await page.getByLabel('Footprint price per row').fill('0');assert.equal(await page.getByLabel('Footprint price per row').getAttribute('aria-invalid'),'true');await page.getByLabel('Footprint price per row').fill('5');
 const before=await page.evaluate(()=>window.__sources.length);assert.equal(before,1);await page.getByLabel('Footprint settings').click();await page.getByLabel('Zoom footprint in').click();await page.getByLabel('Fit footprint',{exact:true}).click();
 for(const width of [768,390,320]){await page.setViewportSize({width,height:950});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'responsive '+width);await page.screenshot({path:path.join(out,`footprint-${width}.png`)})}
 await page.setViewportSize({width:1500,height:1040});await page.getByLabel('Footprint settings').click();await page.getByLabel('Reset footprint capture').click();await page.waitForFunction(()=>document.querySelector('.fp-statbar')?.textContent.includes('Fills0'));await page.getByLabel('Toggle footprint chart').click();assert.ok(await page.locator('.cs-chart-stage').isVisible());await page.waitForFunction(()=>window.__sources.length===0);
 // A Yahoo workspace must not invent aggressor data or open a trade stream.
 await page.evaluate(()=>{const w=JSON.parse(localStorage.getItem('vrp.chart-studio.v1'));w.instrument={provider:'yahoo',symbol:'SPY',name:'SPY'};localStorage.setItem('vrp.chart-studio.v1',JSON.stringify(w))});
 // Override the initial fixture for this reload.
 await page.addInitScript(()=>{const w=JSON.parse(localStorage.getItem('vrp.chart-studio.v1'));w.instrument={provider:'yahoo',symbol:'SPY',name:'SPY'};localStorage.setItem('vrp.chart-studio.v1',JSON.stringify(w))});await page.reload();await page.getByLabel('Toggle footprint chart').click();await page.getByText('Choose a Hyperliquid market',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.__sources.length),0);
 assert.deepEqual(errors,[]);console.log('PASS footprint canvas/DPR, real custom series, levels, imbalance, delta/color/text settings, CSV/PNG exports, capture reset/cleanup, Yahoo guard, mobile widths');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
