const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs'),path=require('path');
const fixture=require('./greeks-indicator-fixture.cjs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
  const page=await browser.newPage({viewport:{width:1500,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const {bars,data}=fixture();
  await page.route('**/api/chart-studio/bars?**',r=>r.fulfill({json:{bars,currency:'USD',timezone:'America/New_York',asOf:Date.now(),note:'Deterministic test fixture'}}));
  await page.route('**/api/chart-studio/stream?**',r=>r.abort());
  await page.route('**/api/greeks/chart-data?**',r=>r.fulfill({json:data}));
  await page.goto('http://127.0.0.1:3000/terminal',{waitUntil:'domcontentloaded'});
  const codes=['the_greeks_complete.py','options_activity_levels.py','greeks_regime_history.py'].map(f=>fs.readFileSync(path.join(__dirname,'../public/chart-studio/indicators',f),'utf8'));
  const result=await page.evaluate(async({codes,bars,data})=>{
    const worker=new Worker('/chart-studio/python-worker.js');let id=0;
    const run=(code,payload,params={})=>new Promise((resolve,reject)=>{const current=++id;const timer=setTimeout(()=>reject(Error('Python timeout')),120000);worker.onmessage=({data:r})=>{if(r.id===current&&(r.result||r.error)){clearTimeout(timer);resolve(r)}};worker.postMessage({id:current,code,payload:{datasets:{chart:bars},symbol:'SPY',interval:'1h',params,greeks:payload}})});
    const outputs=[];for(const code of codes)outputs.push(await run(code,data));
    outputs.push(await run(codes[0],data,{min_oi:100000}));
    outputs.push(await run(codes[0],{...data,meta:{...data.meta,source:'synthetic'}}));
    const cutoff=bars[30].time;const replay={...data,snapshot:null,chain:[],oi_changes:[],meta:{...data.meta,replay:true,cutoff}};
    outputs.push(await run(codes[0],replay));outputs.push(await run(codes[1],replay));
    outputs.push(await run('def calculate(ctx):\n    ctx.plot.hline("x", len(ctx.greeks.history()))',replay));
    const oldHistory={...data,history:data.history.map(r=>({...r,time:r.time-86400*30}))};
    outputs.push(await run(codes[0],oldHistory));outputs.push(await run(codes[2],oldHistory));
    worker.terminate();return outputs;
  },{codes,bars,data});
  for(let i=0;i<3;i++)assert.ok(result[i].result,result[i].error);
  assert.equal(result[0].result.plots.find(p=>p.id==='call_wall').value,105);assert.equal(result[0].result.plots.find(p=>p.id==='put_wall').value,95);
  assert.equal(result[0].result.plots.find(p=>p.id==='max_pain').value,100);
  assert.equal(result[0].result.plots.find(p=>p.id==='gex').data[0].value,null);
  assert.match(result[3].error,/No contracts/);assert.match(result[4].error,/mixed\/synthetic/);
  assert.ok(result[5].result);assert.ok(result[5].result.plots.every(p=>p.kind!=='hline'));
  assert.match(result[6].error,/unavailable in replay/);assert.equal(result[7].result.plots[0].value,30);
  assert.ok(result[8].result.plots.every(p=>p.kind==='hline'));assert.match(result[9].error,/No stored Greeks observations align/);
  await page.getByRole('button',{name:'The Greeks',exact:true}).click();
  await page.getByRole('button',{name:'Use SPY Yahoo chart',exact:true}).click();
  await page.getByRole('button',{name:'Add complete indicator',exact:true}).click();
  await page.getByRole('button',{name:'Run',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.cs-console')?.textContent.includes('Completed'),null,{timeout:120000});
  assert.match(await page.locator('.cs-console-output').innerText(),/THE GREEKS \/ SPY/);
  await page.getByLabel('min_oi',{exact:true}).fill('20');
  await page.getByRole('button',{name:'Run',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.cs-console')?.textContent.includes('Completed'),null,{timeout:30000});
  const download=page.waitForEvent('download');await page.getByLabel('Download Python script').click();assert.ok((await download).suggestedFilename().endsWith('.py'));
  const dest=path.resolve(__dirname,'../../.ua/chart-studio');fs.mkdirSync(dest,{recursive:true});await page.screenshot({path:path.join(dest,'greeks-custom-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'Save',exact:true}).click();await page.reload({waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>document.querySelector('input[aria-label="Greeks source ticker"]')?.value==='SPY');
  await page.getByRole('button',{name:'Open Python Studio',exact:true}).click();
  await page.locator('.cs-script-tabs button').filter({hasText:'The Greeks · Complete'}).click();
  await page.getByRole('button',{name:'Replay',exact:true}).click();await page.getByRole('button',{name:'Next replay candle',exact:true}).click();
  await page.getByRole('button',{name:'Run',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.cs-console')?.textContent.includes('Completed'),null,{timeout:120000});
  assert.match(await page.locator('.cs-console-output').innerText(),/Replay: current chain/);
  for(const width of [768,390]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await page.screenshot({path:path.join(dest,`greeks-custom-${width}.png`),fullPage:true})}
  assert.deepEqual(errors,[]);console.log('PASS 10 real Greek Python cases; UI templates, source, parameters, downloads, persistence, replay and responsive');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
