const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs'),path=require('path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:1500,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const code='def calculate(ctx):\n    b=ctx.data.ohlcv()\n    n=ctx.input.int("length",5,2,40)\n    ctx.plot.line("signal",b.close.rolling(n).mean(),title="Signal average")\n    ctx.plot.area("band",b.close-2,title="Lower band",color="#879cfa")\n    ctx.plot.histogram("momentum",b.close.diff(),pane="Momentum",color="#eab86b")\n    ctx.plot.hline("level",106,title="Reference level")\n    ctx.plot.marker("turn",b.close>b.high.shift(1),text="Turn")\n    ctx.plot.box("zone",b.index[-80],b.index[-50],104,102)';
 await page.addInitScript(code=>{if(!localStorage.getItem('vrp.chart-studio.v1'))localStorage.setItem('vrp.chart-studio.v1',JSON.stringify({version:1,name:'Style test',instrument:{provider:'yahoo',symbol:'SPY',name:'SPY'},interval:'1h',drawings:{},studies:[{id:'style-test',name:'Style Lab',code,params:{},enabled:true,auto:false}],watchlist:[{provider:'yahoo',symbol:'SPY',name:'SPY'}],light:false}));window.__indicatorRuns=0;const Original=window.Worker;window.Worker=class extends Original{postMessage(...args){if(args[0]?.code)window.__indicatorRuns++;return super.postMessage(...args)}}},code);
 const end=Math.floor(Date.now()/3600000)*3600;const bars=Array.from({length:240},(_,i)=>{const open=100+i*.015+Math.sin(i/7),close=open+Math.sin(i)*.35;return {time:end-(239-i)*3600,open,close,high:Math.max(open,close)+.05,low:Math.min(open,close)-.1,volume:100+i}});
 await page.route('**/api/chart-studio/bars?**',r=>r.fulfill({json:{bars,currency:'USD',timezone:'UTC',asOf:Date.now(),note:'Style fixture'}}));await page.route('**/api/chart-studio/stream?**',r=>r.abort());
 await page.goto('http://127.0.0.1:3000/terminal',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!document.querySelector('.cs-chart-empty'));
 await page.getByRole('button',{name:'Configure Style Lab',exact:true}).click();await page.getByRole('button',{name:'Run indicator',exact:true}).click();await page.waitForSelector('[data-plot-style="signal"]',{timeout:120000});assert.equal(await page.evaluate(()=>window.__indicatorRuns),1);
 await page.getByRole('button',{name:'Done',exact:true}).click();await page.evaluate(()=>window.__canvases=Array.from(document.querySelectorAll('.cs-chart-canvas canvas')));
 await page.getByRole('button',{name:'Configure Style Lab',exact:true}).click();await page.getByLabel('Color signal',{exact:true}).fill('#ff00aa');await page.getByLabel('Thickness signal',{exact:true}).selectOption('4');await page.getByLabel('Line style signal',{exact:true}).selectOption('dashed');await page.getByLabel('Label signal',{exact:true}).fill('Custom signal');await page.getByLabel('Price label signal',{exact:true}).uncheck();await page.getByLabel('Price line signal',{exact:true}).check();await page.getByLabel('Line shape signal',{exact:true}).selectOption('step');
 const pixels=()=>page.evaluate(()=>{const c=document.querySelector('.cs-chart-canvas canvas');const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let n=0;for(let i=0;i<d.length;i+=4)if(d[i]>240&&d[i+1]<15&&Math.abs(d[i+2]-170)<12)n++;return n});
 await page.getByRole('button',{name:'Done',exact:true}).click();await page.waitForTimeout(120);assert.ok(await pixels()>100,'style reaches actual chart canvas');assert.equal(await page.evaluate(()=>{const c=document.querySelectorAll('.cs-chart-canvas canvas')[2];const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let count=0;for(let i=0;i<d.length;i+=4)if(d[i]>240&&d[i+1]<15&&Math.abs(d[i+2]-170)<12)count++;return count}),0,'price label toggle hides both title and value');assert.ok(await page.evaluate(()=>window.__canvases.every((c,i)=>c===document.querySelectorAll('.cs-chart-canvas canvas')[i])),'same canvas and panes');
 await page.getByRole('button',{name:'Configure Style Lab',exact:true}).click();await page.getByLabel('Show plot signal',{exact:true}).uncheck();await page.getByRole('button',{name:'Done',exact:true}).click();await page.waitForTimeout(120);assert.equal(await pixels(),0,'hidden series removed from rendering');
 await page.getByRole('button',{name:'Configure Style Lab',exact:true}).click();await page.getByLabel('Show plot signal',{exact:true}).check();await page.getByLabel('Color momentum',{exact:true}).fill('#55ccff');await page.getByLabel('Fill opacity band',{exact:true}).fill('55');await page.getByLabel('Opacity band',{exact:true}).fill('60');await page.getByLabel('Marker shape turn',{exact:true}).selectOption('circle');await page.getByLabel('Marker position turn',{exact:true}).selectOption('belowBar');await page.getByLabel('Marker size turn',{exact:true}).fill('3');await page.getByLabel('Color zone',{exact:true}).fill('#ff9900');await page.getByLabel('Thickness zone',{exact:true}).selectOption('3');await page.getByLabel('Line style zone',{exact:true}).selectOption('dotted');await page.getByLabel('Fill opacity zone',{exact:true}).fill('40');
 await page.getByRole('button',{name:'Done',exact:true}).click();assert.equal(await page.locator('[data-drawing-id="study:style-test:zone"]').getAttribute('stroke'),'#ff9900');assert.equal(await page.locator('[data-drawing-id="study:style-test:zone"]').getAttribute('stroke-width'),'3');assert.equal(await page.evaluate(()=>window.__indicatorRuns),1,'styles do not run Python');
 await page.getByRole('button',{name:'Save',exact:true}).click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('vrp.chart-studio.v1')));assert.equal(saved.studies[0].styles.signal.width,4);assert.equal(saved.studies[0].styles.turn.markerShape,'circle');
 await page.getByRole('button',{name:'Configure Style Lab',exact:true}).click();await page.getByRole('tab',{name:'Inputs',exact:true}).click();await page.getByLabel('Input length',{exact:true}).fill('12');await page.getByRole('button',{name:'Run indicator',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.cs-indicator-message')?.textContent.includes('Style previews'));assert.equal(await page.evaluate(()=>window.__indicatorRuns),2);await page.getByRole('tab',{name:'Style',exact:true}).click();assert.equal(await page.getByLabel('Thickness signal',{exact:true}).inputValue(),'4');
 const out=path.resolve(__dirname,'../../.ua/chart-studio');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'indicator-style-settings.png'),fullPage:true});await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await page.screenshot({path:path.join(out,'indicator-style-chart.png'),fullPage:true});
 await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Configure Style Lab',exact:true}).click();await page.getByRole('button',{name:'Run indicator',exact:true}).click();await page.waitForSelector('[data-plot-style="signal"]',{timeout:120000});assert.equal(await page.getByLabel('Color signal',{exact:true}).inputValue(),'#ff00aa');assert.equal(await page.getByLabel('Thickness signal',{exact:true}).inputValue(),'4');
 await page.getByRole('button',{name:'Reset plot signal',exact:true}).click();assert.equal(await page.getByLabel('Thickness signal',{exact:true}).inputValue(),'1');assert.equal(await page.getByLabel('Color zone',{exact:true}).inputValue(),'#ff9900','plot reset leaves other overrides intact');
 for(const width of [768,390,320]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>{const d=document.querySelector('dialog');return d.scrollWidth<=d.clientWidth+1&&document.documentElement.scrollWidth<=innerWidth+1}));await page.screenshot({path:path.join(out,'indicator-style-'+width+'.png'),fullPage:true})}
 await page.getByRole('button',{name:'Reset style',exact:true}).click();assert.equal(await page.getByLabel('Color zone',{exact:true}).inputValue(),'#45c9b0');assert.deepEqual(errors,[]);console.log('PASS six plot types, native canvas color/visibility, instant styling without Python, stable canvases, inputs Run, persistence, per-plot reset, full reset and responsive dialogs');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
