const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 const stamp=new Date().toISOString(),future=new Date(Date.now()+2*864e5).toISOString(),past=new Date(Date.now()-10*864e5).toISOString();
 const source={name:'Forex Factory',url:'https://nfs.faireconomy.media/ff_calendar_thisweek.json',fetched_at:stamp,stale:false,error:null,count:2};
 const base={precision:'time',source:'Forex Factory',url:'https://www.forexfactory.com/calendar',category:'Inflation',impact:'High',impact_basis:'provider',actual:null,forecast:'0.3%',previous:'0.2%',unit:null,first_seen:stamp,last_seen:stamp};
 const events=[{...base,id:'future',title:'Core CPI m/m',date:future},{...base,id:'past',title:'GDP test release',category:'Growth',date:past,actual:'2.1%',forecast:'2.0%'}];
 const fixture={events,news:[{id:'n',title:'GDP official release',source:'BEA',date:past,url:'https://www.bea.gov/news',category:'Growth'}],sources:[source,{...source,name:'BLS archive',url:'https://www.bls.gov',error:'403 Forbidden',stale:true,fetched_at:null,count:0}],generated_at:stamp};
 const model={key:'core_cpi',series:'CPILFESL',label:'CPI · core',unit:'m/m %',frequency:'M',window:120,strength:4,model_version:'bayes-ar-v1',vintage:'latest revised',source,generated_at:stamp,source_url:'https://fred.stlouisfed.org/series/CPILFESL',input_hash:'fixture',latest:.2,latest_period:'2026-07',target_period:'2026-08',threshold:.2,probability_above:.7,prediction:{mean:.3,lower:.1,upper:.5,training_pairs:120},metrics:{n:48,mae:.1,rmse:.15,naive_mae:.08,skill:-.25,coverage:.8},evaluation:Array.from({length:48},(_,i)=>({period:`period-${i}`,actual:.2+Math.sin(i)*.1,model:.3,naive:.2,lower:.1,upper:.5})),history:[{period:'2026-07',value:.2}]};
 let fail=false;
 await page.route('**/api/**',route=>route.fulfill({status:503,json:{detail:'Unrelated service unavailable'}}));
 await page.route('**/api/macro/**',route=>{const u=new URL(route.request().url());if(u.pathname.endsWith('/dashboard'))return route.fulfill({json:fixture});if(u.pathname.includes('/revisions/'))return route.fulfill({json:[{observed_at:stamp,event:events[0]}]});if(fail)return route.fulfill({status:502,json:{detail:'FRED fixture offline'}});return route.fulfill({json:{...model,threshold:Number(u.searchParams.get('threshold')||.2)}})});
 await page.goto('http://127.0.0.1:3000/?view=macro',{waitUntil:'domcontentloaded'});
 const command=page.getByRole('combobox',{name:'Terminal command'});await command.waitFor();
 await page.getByRole('heading',{name:'Upcoming catalysts'}).waitFor();assert.equal(await command.inputValue(),'ECO');
 await page.getByRole('button',{name:'Core CPI m/m',exact:true}).click();await page.getByRole('heading',{name:'Observed changes'}).waitFor();
 assert.match(await page.getByLabel('Release details').innerText(),/Actual\s+—/);
 await page.getByRole('button',{name:'Close details'}).click();
 await page.getByLabel('Calendar timezone').selectOption('Asia/Jakarta');
 assert.match(await page.locator('table').innerText(),/Core CPI/);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV',exact:true}).click();assert.match((await download).suggestedFilename(),/usd-calendar/);
 await page.getByRole('button',{name:'Release history',exact:true}).click();await page.getByRole('button',{name:'GDP test release'}).waitFor();
 await page.getByLabel('Search releases').fill('no-match');await page.getByText(/No releases match/).waitFor();await page.getByLabel('Search releases').fill('');
 await page.getByRole('button',{name:'Forecast Lab',exact:true}).click();await page.getByText('0.30',{exact:false}).first().waitFor();
 await page.getByLabel('Training window').selectOption('60');
 await page.getByLabel('Prior strength').selectOption('16');await page.getByLabel('Scenario threshold').fill('0.4');await page.getByRole('button',{name:'Evaluate',exact:true}).click();await page.getByText('P(NEXT VALUE > 0.40)',{exact:true}).waitFor();
 assert.ok(requests.some(u=>u.includes('strength=16')));assert.ok(requests.some(u=>u.includes('window=60')));
 fail=true;await page.getByLabel('Economic series').selectOption('payrolls');await page.getByText('FRED fixture offline',{exact:false}).waitFor();fail=false;await page.getByRole('button',{name:'Retry forecast'}).click();await page.getByRole('heading',{name:'Walk-forward evaluation'}).waitFor();
 const out=path.join(__dirname,'../../.ua/macro');fs.mkdirSync(out,{recursive:true});
 await page.screenshot({path:path.join(out,'forecast-fixture.png'),fullPage:true});
 for(const width of [320,768,1024,1440]){await page.setViewportSize({width,height:950});await page.waitForTimeout(200);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow at ${width}`);await page.screenshot({path:path.join(out,`forecast-${width}.png`),fullPage:true})}
 await page.getByRole('button',{name:'News & context',exact:true}).click();await page.getByRole('link',{name:'GDP official release'}).waitFor();
 await page.getByRole('button',{name:'Data coverage',exact:true}).click();await page.getByText('UNAVAILABLE',{exact:true}).waitFor();
 await command.fill('SPY ECO');await command.press('Enter');await page.getByRole('alert').filter({hasText:'selects instruments inside'}).waitFor();
 await command.fill('SPY GEX');await command.press('Enter');await page.waitForURL('**view=gex**');await command.fill('ECO');await command.press('Enter');await page.waitForURL('**view=macro**');await page.goBack();await page.waitForURL('**view=gex**');await page.goForward();await page.waitForURL('**view=macro**');await page.reload();await page.getByRole('heading',{name:'Upcoming catalysts'}).waitFor();
 assert.equal(errors.length,0,errors.join('\n'));console.log('PASS macro calendar, model controls, missing data, errors, exports, responsiveness and ECO navigation');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
