const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));
 const stamp='2026-09-11T08:00:00Z',source={url:'https://fred.stlouisfed.org/series/CPILFESL',fetched_at:'2026-09-09T12:29:28Z',stale:true,error:'ConnectTimeout fixture'};
 const evaluation=[0,.4,1,2.5,-2.5].map((z,i)=>({period:`2026-0${i+1}`,actual:.3+z*.1,model:.3,naive:.2,lower:.17,upper:.43,surprise:z*.1,predictive_sd:.1,model_z:z}));
 const model={key:'core_cpi',series:'CPILFESL',label:'CPI · core',unit:'m/m %',frequency:'M',window:120,strength:4,model_version:'bayes-ar-v1',vintage:'latest revised',source,generated_at:stamp,source_url:source.url,input_hash:'fixture',latest:.05,latest_period:'2026-05',target_period:'2026-06',threshold:.2,probability_above:.7,prediction:{mean:.3,lower:.1,upper:.5,training_pairs:120},metrics:{n:5,mae:.1,rmse:.15,naive_mae:.08,skill:-.25,coverage:.8},evaluation,history:[{period:'2026-05',value:.05}]};
 await page.route('**/api/**',r=>r.fulfill({status:503,json:{detail:'Unrelated service unavailable'}}));
 await page.route('**/api/macro/**',r=>{
  const u=new URL(r.request().url());requests.push(u);
  if(u.pathname.endsWith('/dashboard'))return r.fulfill({json:{events:[],news:[],sources:[],generated_at:stamp}});
  if(u.pathname.endsWith('/forecast-history'))return r.fulfill({json:[{generated_at:stamp,target_period:'2026-06',mean:.3,lower:.1,upper:.5,window:120,strength:4,input_hash:'fixture',source_fetched_at:stamp,source_stale:false}]});
  return r.fulfill({json:{...model,source:u.searchParams.get('refresh')==='true'?{...source,stale:false,error:null,fetched_at:stamp}:source}});
 });
 await page.goto('http://127.0.0.1:3000/?view=macro',{waitUntil:'domcontentloaded'});
 await page.getByRole('button',{name:'Forecast Lab',exact:true}).click();
 const history=page.getByRole('region',{name:'Model surprise history'}),table=history.locator('table');
 await history.getByRole('heading',{name:'Histori surprise model'}).waitFor();
 assert.match(await page.innerText('body'),/FRED belum berhasil diperbarui/);
 assert.equal(await table.locator('tbody tr').count(),5);
 assert.equal(await table.getByText('Netral',{exact:true}).count(),2);
 assert.equal(await table.getByText('Bullish shock USD',{exact:true}).count(),1);
 assert.match(await table.locator('tbody tr').first().innerText(),/Bearish shock USD/);
 await page.getByLabel('Asumsi arah USD').selectOption('-1');
 assert.match(await table.locator('tbody tr').first().innerText(),/Bullish shock USD/);
 await page.getByLabel('Batas netral model').selectOption('1');
 assert.equal(await table.getByText('Netral',{exact:true}).count(),3);
 await page.getByLabel('Batas shock model').selectOption('3');
 assert.equal(await table.getByText(/shock USD/).count(),0);
 await page.getByLabel('Filter label model').selectOption('Shock');
 await history.getByText('Tidak ada periode yang cocok dengan filter ini.').waitFor();
 await page.getByLabel('Batas shock model').selectOption('2');
 assert.equal(await table.locator('tbody tr').count(),2);
 const download=page.waitForEvent('download');await history.getByRole('button',{name:'Export histori model'}).click();
 const file=await download,body=fs.readFileSync(await file.path(),'utf8');
 assert.match(file.suggestedFilename(),/model-surprise.csv/);assert.match(body,/usd_direction/);assert.match(body,/latest revised \/ reconstructed/);assert.match(body,/Bullish shock USD/);
 await history.getByRole('button',{name:'Forecast tersimpan'}).click();
 await table.getByText('120 observasi · prior 4').waitFor();assert.match(await table.innerText(),/2026-06/);
 assert.ok(requests.some(u=>u.pathname.endsWith('/forecast-history')));
 await history.getByRole('button',{name:'Histori evaluasi'}).click();
 await page.getByLabel('Filter label model').selectOption('Semua');
 await page.getByRole('button',{name:'Refresh data FRED',exact:true}).click();
 await page.waitForFunction(()=>!document.body.innerText.includes('FRED belum berhasil diperbarui')&&document.body.innerText.includes('Histori surprise model'));
 assert.ok(requests.some(u=>u.searchParams.get('refresh')==='true'));
 const out=path.join(__dirname,'../../.ua/macro');fs.mkdirSync(out,{recursive:true});
 for(const width of [320,768,1024,1440]){await page.setViewportSize({width,height:950});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(200);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow at ${width}`);await page.screenshot({path:path.join(out,`model-surprise-${width}.png`),fullPage:true});}
 assert.deepEqual(errors,[]);console.log('PASS model surprise labels, orientation, thresholds, filtering, saved snapshots, CSV, FRED recovery and responsive layouts');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
