const {chromium}=require('playwright'); const assert=require('node:assert/strict'); const fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/'))requests.push(r.url())});
 await page.route('**/api/**',r=>r.fulfill({status:503,json:{error:'Test feed unavailable',detail:'Test feed unavailable'}}));
 await page.route('**/api/chart-studio/search?*',r=>r.fulfill({json:[{provider:'hyperliquid',symbol:'xyz:TSLA',name:'Tesla',venue:'xyz',collateral:'USDC'}]}));
 await page.route('**/api/chart-studio/bars?*',r=>r.fulfill({json:{bars:Array.from({length:180},(_,i)=>({time:1700000000+i*3600,open:100+i/10,close:101+i/10,high:102+i/10,low:99+i/10,volume:1000+i})),currency:'USD',timezone:'UTC',asOf:Date.now()}}));
 await page.route('**/api/chart-studio/stream?*',r=>r.abort());
 const command=page.getByRole('combobox',{name:'Terminal command'});const header=page.locator('header').first();
 async function run(text,view,ticker){await command.fill(text);await command.press('Enter');if(view)await page.waitForURL(u=>u.searchParams.get('view')===view&&(!ticker||u.searchParams.get('ticker')===ticker));}
 async function position(value){await page.getByLabel('Navigation position').filter({hasText:value}).waitFor();}
 await page.goto('http://127.0.0.1:3000/?view=greeks&ticker=QQQ&keep=yes',{waitUntil:'domcontentloaded'});await page.waitForURL('**view=gex**');assert.equal(await command.inputValue(),'QQQ GEX');await position('1 / 1');
 assert.ok(!requests.some(u=>u.includes('/api/vrp?')),'deep link must not fetch default VRP first');
 await run('nvda gp','gp','NVDA');await page.waitForSelector('.cs-chart-canvas canvas');assert.match(await page.locator('.cs-symbol-button').innerText(),/NVDA/);assert.ok(requests.some(u=>u.includes('symbol=NVDA')&&u.includes('provider=yahoo')));await position('2 / 2');
 await run('nvda gp','gp','NVDA');await position('2 / 2');
 await run('NVDA TYPO');assert.equal(new URL(page.url()).searchParams.get('view'),'gp');await page.getByRole('alert').filter({hasText:'Unknown function'}).waitFor();await position('2 / 2');
 await run('SPY COT');await page.getByRole('alert').filter({hasText:'selects instruments inside'}).waitFor();
 await run('SPY VRP','vrp','SPY');await position('3 / 3');await header.getByRole('button',{name:'Back',exact:true}).click();await page.waitForURL('**view=gp**');await position('2 / 3');assert.equal(await command.inputValue(),'NVDA GP');
 await page.goBack();await page.waitForURL('**view=gex**');await position('1 / 3');await page.goForward();await page.waitForURL('**view=gp**');await position('2 / 3');
 await run('GEX TSLA','gex','TSLA');await position('3 / 3');assert.equal(await header.getByRole('button',{name:'Forward',exact:true}).isDisabled(),true);assert.equal(new URL(page.url()).searchParams.get('keep'),'yes');
 await header.getByRole('button',{name:'Favorite current command'}).click();assert.equal(await header.getByRole('button',{name:'Favorite current command'}).getAttribute('aria-pressed'),'true');
 await page.reload({waitUntil:'domcontentloaded'});await command.waitFor();await page.waitForFunction(()=>document.querySelector('input[aria-label="Terminal command"]')?.value==='TSLA GEX');await position('3 / 3');assert.equal(await header.getByRole('button',{name:'Favorite current command'}).getAttribute('aria-pressed'),'true');
 await page.keyboard.press('Control+k');assert.equal(await command.evaluate(el=>el===document.activeElement),true);await command.fill('chart studio');await command.press('ArrowDown');await command.press('Enter');await page.waitForURL('**view=gp**');await page.waitForSelector('.cs-chart-canvas canvas');
 await page.getByLabel('Workspace name').fill('Unsaved controller workspace');await Promise.all([page.waitForRequest(r=>r.url().includes('symbol=xyz%3ATSLA')&&r.url().includes('provider=hyperliquid')),run('XYZ:tsla GP','gp','xyz:TSLA')]);await page.waitForFunction(()=>document.querySelector('.cs-symbol-button')?.textContent.includes('xyz:TSLA'));assert.ok(requests.some(u=>u.includes('symbol=xyz%3ATSLA')&&u.includes('provider=hyperliquid')));assert.equal(await page.getByLabel('Workspace name').inputValue(),'Unsaved controller workspace');
 await run('SPY GP','gp','SPY');await page.waitForFunction(()=>document.querySelector('.cs-symbol-button')?.textContent.includes('SPY'));
 await page.keyboard.press('F1');await page.getByRole('dialog').waitFor();await page.getByLabel('Search function directory').fill('correlation');assert.equal(await page.getByRole('dialog').getByRole('button').count(),2);await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
 await page.keyboard.press('F1');await page.getByLabel('Search function directory').fill('no match xyz');await page.getByText('No function found.',{exact:false}).waitFor();await page.getByLabel('Search function directory').fill('');
 const out=path.resolve(__dirname,'../../.ua/terminal-controller');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'directory-desktop.png')});
 for(const width of [768,390,320]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>{const d=document.querySelector('dialog[open]');return d.scrollWidth<=d.clientWidth+1&&document.documentElement.scrollWidth<=innerWidth+1}),'directory width '+width);await page.screenshot({path:path.join(out,`directory-${width}.png`)});}
 await page.keyboard.press('Escape');await run('SPY VRP','vrp','SPY');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:950});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'page width '+width);await page.keyboard.press('Control+k');await command.fill('SPY G');assert.equal(await page.getByRole('listbox').isVisible(),true);await page.screenshot({path:path.join(out,`controller-${width}.png`)});await command.press('Escape');}
 await run('QQQ VRP','vrp','QQQ');const before=requests.filter(u=>u.includes('/api/vrp?')).length;await header.getByRole('button',{name:'Reload current module'}).click();await page.waitForTimeout(300);assert.ok(requests.filter(u=>u.includes('/api/vrp?')).length>before,'explicit reload fetches');
 await run('NVDA VOL','vol','NVDA');await page.getByLabel('Volatility ticker').waitFor();assert.equal(await page.getByLabel('Volatility ticker').inputValue(),'NVDA');await page.getByLabel('Volatility ticker').fill('QQQ');await page.waitForURL('**ticker=QQQ**');assert.equal(await command.inputValue(),'QQQ VOL');await run('QQQ VRP','vrp','QQQ');
 await page.context().grantPermissions(['clipboard-read','clipboard-write']);await header.getByRole('button',{name:'Copy page link'}).click();await page.getByRole('status').filter({hasText:'Link copied'}).waitFor();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),page.url());
 const guide=await page.request.get('http://127.0.0.1:3000/terminal/agents.md');assert.equal(guide.status(),200);assert.match(await guide.text(),/single function registry/);
 await page.evaluate(()=>{localStorage.setItem('vrp.terminal.commands.v1','{broken');sessionStorage.setItem('vrp.terminal.commands.v1.history','{"entries":[null]}')});await page.reload();await page.waitForFunction(()=>document.querySelector('input[aria-label="Terminal command"]')?.value==='QQQ VRP');await position('1 / 1');
 assert.deepEqual(errors,[]);console.log('PASS: URL aliases, actual GP ticker/provider, invalid commands, duplicate suppression, branching browser history, reload persistence, pins, keyboard search, directory, refresh and responsive 320/390/768/1440');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
